// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Help
{
	/// <summary>
	/// RCP method help.setBotUpdatesStatus.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHelpSetBotUpdatesStatus : ITLObject, TLHelpSetBotUpdatesStatus
	{
		public Int32 PendingUpdatesCount { get; set; }
		public String Message { get; set; }

		public ITLHelpSetBotUpdatesStatus() { }
		public ITLHelpSetBotUpdatesStatus(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpSetBotUpdatesStatus; } }

		public override void Read(TLBinaryReader from)
		{
			PendingUpdatesCount = from.ReadInt32();
			Message = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEC22CFCD);
			to.Write(PendingUpdatesCount);
			to.Write(Message);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLHelpSetBotUpdatesStatus : TLObject
	{
		Int32 PendingUpdatesCount { get; set; }
		String Message { get; set; }
	}
#endif

}