// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Help
{
	/// <summary>
	/// RCP method help.getAppChangelog.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHelpGetAppChangelog : ITLObject, TLHelpGetAppChangelog
	{
		public String PrevAppVersion { get; set; }

		public ITLHelpGetAppChangelog() { }
		public ITLHelpGetAppChangelog(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpGetAppChangelog; } }

		public override void Read(TLBinaryReader from)
		{
			PrevAppVersion = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9010EF6F);
			to.Write(PrevAppVersion);
		}
	}

#if !PORTABLE
	[Guid(0xd35752d0, 0x0452, 0x6165, 0xb5, 0xbf, 0xa2, 0x65, 0x03, 0x22, 0xd8, 0x2d)]
	public partial interface TLHelpGetAppChangelog : TLObject
	{
		String PrevAppVersion { get; set; }
	}
#endif

}