// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Help
{
	/// <summary>
	/// RCP method help.saveAppLog.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHelpSaveAppLog : ITLObject, TLHelpSaveAppLog
	{
		public TLVector<TLInputAppEvent> Events { get; set; }

		public ITLHelpSaveAppLog() { }
		public ITLHelpSaveAppLog(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpSaveAppLog; } }

		public override void Read(TLBinaryReader from)
		{
			Events = TLFactory.Read<TLVector<TLInputAppEvent>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x6F02F748);
			to.WriteObject(Events);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLHelpSaveAppLog : TLObject
	{
		TLVector<TLInputAppEvent> Events { get; set; }
	}
#endif

}