// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Help
{
	/// <summary>
	/// RCP method help.getTermsOfService.
	/// Returns <see cref="Telegram.Api.TL.TLHelpTermsOfService"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHelpGetTermsOfService : ITLObject, TLHelpGetTermsOfService
	{
		public ITLHelpGetTermsOfService() { }
		public ITLHelpGetTermsOfService(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpGetTermsOfService; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x350170F3);
		}
	}

#if !PORTABLE
	[Guid(0x2dadfd95, 0x0b35, 0xf6e0, 0x89, 0x88, 0x82, 0x18, 0xf0, 0x31, 0x8b, 0xd8)]
	public partial interface TLHelpGetTermsOfService : TLObject
	{
	}
#endif

}