// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Help
{
	/// <summary>
	/// RCP method help.getConfig.
	/// Returns <see cref="Telegram.Api.TL.TLConfig"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHelpGetConfig : ITLObject, TLHelpGetConfig
	{
		public ITLHelpGetConfig() { }
		public ITLHelpGetConfig(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpGetConfig; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC4F9186B);
		}
	}

#if !PORTABLE
	[Guid(0x32024522, 0xae65, 0xf84c, 0x7d, 0x02, 0xc8, 0xb6, 0xba, 0x99, 0x11, 0x39)]
	public partial interface TLHelpGetConfig : TLObject
	{
	}
#endif

}