// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Help
{
	/// <summary>
	/// RCP method help.getInviteText.
	/// Returns <see cref="Telegram.Api.TL.TLHelpInviteText"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHelpGetInviteText : ITLObject, TLHelpGetInviteText
	{
		public ITLHelpGetInviteText() { }
		public ITLHelpGetInviteText(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpGetInviteText; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4D392343);
		}
	}

#if !PORTABLE
	[Guid(0x8f95e035, 0xff3c, 0xc86f, 0xbb, 0x83, 0x76, 0xfb, 0x31, 0xc3, 0xf0, 0xe6)]
	public partial interface TLHelpGetInviteText : TLObject
	{
	}
#endif

}