// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Help
{
	/// <summary>
	/// RCP method help.getAppUpdate.
	/// Returns <see cref="Telegram.Api.TL.TLHelpAppUpdate"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHelpGetAppUpdate : ITLObject, TLHelpGetAppUpdate
	{
		public ITLHelpGetAppUpdate() { }
		public ITLHelpGetAppUpdate(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpGetAppUpdate; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xAE2DE196);
		}
	}

#if !PORTABLE
	[Guid(0x64100e49, 0xd256, 0x1926, 0xc1, 0xab, 0x12, 0x91, 0x60, 0x44, 0x22, 0xb7)]
	public partial interface TLHelpGetAppUpdate : TLObject
	{
	}
#endif

}