// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Photos
{
	/// <summary>
	/// RCP method photos.deletePhotos.
	/// Returns <see cref="Telegram.Api.TL.TLVector<TLlong>"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPhotosDeletePhotos : ITLObject, TLPhotosDeletePhotos
	{
		public TLVector<TLInputPhotoBase> Id { get; set; }

		public ITLPhotosDeletePhotos() { }
		public ITLPhotosDeletePhotos(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhotosDeletePhotos; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLVector<TLInputPhotoBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x87CF7F2F);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0x700b902d, 0xc657, 0x07f5, 0xab, 0x50, 0xd4, 0xd0, 0x53, 0x7a, 0xa0, 0xaf)]
	public partial interface TLPhotosDeletePhotos : TLObject
	{
		TLVector<TLInputPhotoBase> Id { get; set; }
	}
#endif

}