// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Photos
{
	/// <summary>
	/// RCP method photos.updateProfilePhoto.
	/// Returns <see cref="Telegram.Api.TL.TLUserProfilePhotoBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPhotosUpdateProfilePhoto : ITLObject, TLPhotosUpdateProfilePhoto
	{
		public TLInputPhotoBase Id { get; set; }

		public ITLPhotosUpdateProfilePhoto() { }
		public ITLPhotosUpdateProfilePhoto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhotosUpdateProfilePhoto; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLInputPhotoBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF0BB5152);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0xd5eac316, 0x0b21, 0x7f27, 0x82, 0x7c, 0x72, 0x38, 0x87, 0x2d, 0x4b, 0x8a)]
	public partial interface TLPhotosUpdateProfilePhoto : TLObject
	{
		TLInputPhotoBase Id { get; set; }
	}
#endif

}