// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.updateNotifySettings.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountUpdateNotifySettings : ITLObject, TLAccountUpdateNotifySettings
	{
		public TLInputNotifyPeerBase Peer { get; set; }
		public TLInputPeerNotifySettings Settings { get; set; }

		public ITLAccountUpdateNotifySettings() { }
		public ITLAccountUpdateNotifySettings(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountUpdateNotifySettings; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputNotifyPeerBase>(from);
			Settings = TLFactory.Read<TLInputPeerNotifySettings>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x84BE5B93);
			to.WriteObject(Peer);
			to.WriteObject(Settings);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLAccountUpdateNotifySettings : TLObject
	{
		TLInputNotifyPeerBase Peer { get; set; }
		TLInputPeerNotifySettings Settings { get; set; }
	}
#endif

}