// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.reportPeer.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountReportPeer : ITLObject, TLAccountReportPeer
	{
		public TLInputPeerBase Peer { get; set; }
		public TLReportReasonBase Reason { get; set; }

		public ITLAccountReportPeer() { }
		public ITLAccountReportPeer(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountReportPeer; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputPeerBase>(from);
			Reason = TLFactory.Read<TLReportReasonBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xAE189D5F);
			to.WriteObject(Peer);
			to.WriteObject(Reason);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLAccountReportPeer : TLObject
	{
		TLInputPeerBase Peer { get; set; }
		TLReportReasonBase Reason { get; set; }
	}
#endif

}