// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.checkUsername.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountCheckUsername : ITLObject, TLAccountCheckUsername
	{
		public String Username { get; set; }

		public ITLAccountCheckUsername() { }
		public ITLAccountCheckUsername(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountCheckUsername; } }

		public override void Read(TLBinaryReader from)
		{
			Username = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x2714D86C);
			to.Write(Username);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLAccountCheckUsername : TLObject
	{
		String Username { get; set; }
	}
#endif

}