// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.getAccountTTL.
	/// Returns <see cref="Telegram.Api.TL.TLAccountDaysTTL"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountGetAccountTTL : ITLObject, TLAccountGetAccountTTL
	{
		public ITLAccountGetAccountTTL() { }
		public ITLAccountGetAccountTTL(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountGetAccountTTL; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x8FC711D);
		}
	}

#if !PORTABLE
	[Guid(0x3ed1ceea, 0x9f08, 0xebeb, 0xb5, 0x4e, 0x24, 0x35, 0xcf, 0x77, 0x57, 0x4c)]
	public partial interface TLAccountGetAccountTTL : TLObject
	{
	}
#endif

}