// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.updateUsername.
	/// Returns <see cref="Telegram.Api.TL.TLUserBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountUpdateUsername : ITLObject, TLAccountUpdateUsername
	{
		public String Username { get; set; }

		public ITLAccountUpdateUsername() { }
		public ITLAccountUpdateUsername(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountUpdateUsername; } }

		public override void Read(TLBinaryReader from)
		{
			Username = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3E0BDD7C);
			to.Write(Username);
		}
	}

#if !PORTABLE
	[Guid(0xb1cb11ee, 0x5290, 0x0be4, 0x07, 0xaa, 0xc0, 0xca, 0x06, 0x0c, 0x23, 0xee)]
	public partial interface TLAccountUpdateUsername : TLObject
	{
		String Username { get; set; }
	}
#endif

}