// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.confirmPhone.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountConfirmPhone : ITLObject, TLAccountConfirmPhone
	{
		public String PhoneCodeHash { get; set; }
		public String PhoneCode { get; set; }

		public ITLAccountConfirmPhone() { }
		public ITLAccountConfirmPhone(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountConfirmPhone; } }

		public override void Read(TLBinaryReader from)
		{
			PhoneCodeHash = from.ReadString();
			PhoneCode = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x5F2178C3);
			to.Write(PhoneCodeHash);
			to.Write(PhoneCode);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLAccountConfirmPhone : TLObject
	{
		String PhoneCodeHash { get; set; }
		String PhoneCode { get; set; }
	}
#endif

}