// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.getAuthorizations.
	/// Returns <see cref="Telegram.Api.TL.TLAccountAuthorizations"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountGetAuthorizations : ITLObject, TLAccountGetAuthorizations
	{
		public ITLAccountGetAuthorizations() { }
		public ITLAccountGetAuthorizations(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountGetAuthorizations; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE320C158);
		}
	}

#if !PORTABLE
	[Guid(0x70855ee6, 0x5374, 0x4d4b, 0x72, 0x55, 0xd9, 0x68, 0x73, 0x7c, 0x21, 0x8a)]
	public partial interface TLAccountGetAuthorizations : TLObject
	{
	}
#endif

}