// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.getWallPapers.
	/// Returns <see cref="Telegram.Api.TL.TLVector<TLWallPaper>"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountGetWallPapers : ITLObject, TLAccountGetWallPapers
	{
		public ITLAccountGetWallPapers() { }
		public ITLAccountGetWallPapers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountGetWallPapers; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC04CFAC2);
		}
	}

#if !PORTABLE
	[Guid(0xb03cff78, 0x71df, 0xbb8e, 0xec, 0x2a, 0xc2, 0xb7, 0xc1, 0x77, 0x3e, 0x7c)]
	public partial interface TLAccountGetWallPapers : TLObject
	{
	}
#endif

}