// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Contacts
{
	/// <summary>
	/// RCP method contacts.unblock.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsUnblock : ITLObject, TLContactsUnblock
	{
		public TLInputUserBase Id { get; set; }

		public ITLContactsUnblock() { }
		public ITLContactsUnblock(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsUnblock; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLInputUserBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE54100BD);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLContactsUnblock : TLObject
	{
		TLInputUserBase Id { get; set; }
	}
#endif

}