// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Contacts
{
	/// <summary>
	/// RCP method contacts.getStatuses.
	/// Returns <see cref="Telegram.Api.TL.TLVector<TLContactStatus>"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsGetStatuses : ITLObject, TLContactsGetStatuses
	{
		public ITLContactsGetStatuses() { }
		public ITLContactsGetStatuses(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsGetStatuses; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC4A353EE);
		}
	}

#if !PORTABLE
	[Guid(0xfe9ad122, 0x26be, 0x0ace, 0x75, 0x1b, 0x68, 0x1e, 0xbb, 0x85, 0xb6, 0x2d)]
	public partial interface TLContactsGetStatuses : TLObject
	{
	}
#endif

}