// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Contacts
{
	/// <summary>
	/// RCP method contacts.deleteContact.
	/// Returns <see cref="Telegram.Api.TL.TLContactsLink"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsDeleteContact : ITLObject, TLContactsDeleteContact
	{
		public TLInputUserBase Id { get; set; }

		public ITLContactsDeleteContact() { }
		public ITLContactsDeleteContact(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsDeleteContact; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLInputUserBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x8E953744);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0xd65874ff, 0x0353, 0x9504, 0xe9, 0x0a, 0x7d, 0xf8, 0x47, 0x2f, 0xd2, 0xd3)]
	public partial interface TLContactsDeleteContact : TLObject
	{
		TLInputUserBase Id { get; set; }
	}
#endif

}