// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Contacts
{
	/// <summary>
	/// RCP method contacts.importCard.
	/// Returns <see cref="Telegram.Api.TL.TLUserBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsImportCard : ITLObject, TLContactsImportCard
	{
		public TLVector<Int32> ExportCard { get; set; }

		public ITLContactsImportCard() { }
		public ITLContactsImportCard(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsImportCard; } }

		public override void Read(TLBinaryReader from)
		{
			ExportCard = TLFactory.Read<TLVector<Int32>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4FE196FE);
			to.WriteObject(ExportCard);
		}
	}

#if !PORTABLE
	[Guid(0xb1cb11ee, 0x5290, 0x0be4, 0x07, 0xaa, 0xc0, 0xca, 0x06, 0x0c, 0x23, 0xee)]
	public partial interface TLContactsImportCard : TLObject
	{
		TLVector<Int32> ExportCard { get; set; }
	}
#endif

}