// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Contacts
{
	/// <summary>
	/// RCP method contacts.exportCard.
	/// Returns <see cref="Telegram.Api.TL.TLVector<TLint>"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsExportCard : ITLObject, TLContactsExportCard
	{
		public ITLContactsExportCard() { }
		public ITLContactsExportCard(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsExportCard; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x84E53737);
		}
	}

#if !PORTABLE
	[Guid(0xbb17783a, 0x34ce, 0xed5d, 0xf6, 0x10, 0x99, 0xdd, 0x35, 0xac, 0x5e, 0x66)]
	public partial interface TLContactsExportCard : TLObject
	{
	}
#endif

}