// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Contacts
{
	/// <summary>
	/// RCP method contacts.getBlocked.
	/// Returns <see cref="Telegram.Api.TL.TLContactsBlocked"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsGetBlocked : ITLObject, TLContactsGetBlocked
	{
		public Int32 Offset { get; set; }
		public Int32 Limit { get; set; }

		public ITLContactsGetBlocked() { }
		public ITLContactsGetBlocked(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsGetBlocked; } }

		public override void Read(TLBinaryReader from)
		{
			Offset = from.ReadInt32();
			Limit = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF57C350F);
			to.Write(Offset);
			to.Write(Limit);
		}
	}

#if !PORTABLE
	[Guid(0x8dfb760e, 0x3780, 0x8ccc, 0xd7, 0x9c, 0x22, 0x98, 0x11, 0xd9, 0x35, 0x7f)]
	public partial interface TLContactsGetBlocked : TLObject
	{
		Int32 Offset { get; set; }
		Int32 Limit { get; set; }
	}
#endif

}