// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountPasswordSettings : ITLObject, TLAccountPasswordSettings 
	{
		public String Email { get; set; }

		public ITLAccountPasswordSettings() { }
		public ITLAccountPasswordSettings(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountPasswordSettings; } }

		public override void Read(TLBinaryReader from)
		{
			Email = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB7B72AB3);
			to.Write(Email);
		}
	}

#if !PORTABLE
	[Guid(0xe98db03a, 0x2859, 0x3851, 0xa1, 0xc2, 0x3a, 0xa9, 0x48, 0xa8, 0x9c, 0x52)]
	public partial interface TLAccountPasswordSettings : TLObject
	{
		String Email { get; set; }
	}
#endif

}