// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountDaysTTL : ITLObject, TLAccountDaysTTL 
	{
		public Int32 Days { get; set; }

		public ITLAccountDaysTTL() { }
		public ITLAccountDaysTTL(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountDaysTTL; } }

		public override void Read(TLBinaryReader from)
		{
			Days = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB8D0AFDF);
			to.Write(Days);
		}
	}

#if !PORTABLE
	[Guid(0x3ed1ceea, 0x9f08, 0xebeb, 0xb5, 0x4e, 0x24, 0x35, 0xcf, 0x77, 0x57, 0x4c)]
	public partial interface TLAccountDaysTTL : TLObject
	{
		Int32 Days { get; set; }
	}
#endif

}