// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountNoPassword : ITLAccountPasswordBase, TLAccountNoPassword 
	{
		public ITLAccountNoPassword() { }
		public ITLAccountNoPassword(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountNoPassword; } }

		public override void Read(TLBinaryReader from)
		{
			NewSalt = from.ReadByteArray();
			EmailUnconfirmedPattern = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x96DABC18);
			to.WriteByteArray(NewSalt);
			to.Write(EmailUnconfirmedPattern);
		}
	}

#if !PORTABLE
	[Guid(0x16f5f42f, 0x06c5, 0xbe17, 0x5c, 0x42, 0x9e, 0xd3, 0x50, 0x84, 0x34, 0x7a)]
	public partial interface TLAccountNoPassword : TLAccountPasswordBase
	{
		Byte[] NewSalt { get; set; }
		String EmailUnconfirmedPattern { get; set; }
	}
#endif

}