// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAccountPrivacyRules : ITLObject, TLAccountPrivacyRules 
	{
		public TLVector<TLPrivacyRuleBase> Rules { get; set; }
		public TLVector<TLUserBase> Users { get; set; }

		public ITLAccountPrivacyRules() { }
		public ITLAccountPrivacyRules(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountPrivacyRules; } }

		public override void Read(TLBinaryReader from)
		{
			Rules = TLFactory.Read<TLVector<TLPrivacyRuleBase>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x554ABB6F);
			to.WriteObject(Rules);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0xbd1aa7c9, 0x72a2, 0x6afc, 0x80, 0xd4, 0x26, 0x2b, 0xb1, 0x46, 0x14, 0x45)]
	public partial interface TLAccountPrivacyRules : TLObject
	{
		TLVector<TLPrivacyRuleBase> Rules { get; set; }
		TLVector<TLUserBase> Users { get; set; }
	}
#endif

}