// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAuthCodeTypeSms : ITLAuthCodeTypeBase, TLAuthCodeTypeSms 
	{
		public ITLAuthCodeTypeSms() { }
		public ITLAuthCodeTypeSms(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AuthCodeTypeSms; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x72A3158C);
		}
	}

#if !PORTABLE
	[Guid(0x9c64f89e, 0x06ad, 0x92b6, 0x45, 0x62, 0x96, 0x42, 0x1b, 0xac, 0x3a, 0x47)]
	public partial interface TLAuthCodeTypeSms : TLAuthCodeTypeBase
	{
	}
#endif

}