// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
	#else
	public
#endif
	abstract partial class ITLBotInlineResultBase : ITLObject, TLBotInlineResultBase
	{
		public String Id { get; set; }
		public String Type { get; set; }
		public String Title { get; set; }
		public String Description { get; set; }
		public TLBotInlineMessageBase SendMessage { get; set; }
	}

#if !PORTABLE
	[Guid(0x540a2843, 0x7bb2, 0x02b0, 0x93, 0xdf, 0xae, 0xec, 0x54, 0x84, 0x8c, 0x96)]
	public partial interface TLBotInlineResultBase : TLObject
	{
		String Id { get; set; }
		String Type { get; set; }
		String Title { get; set; }
		String Description { get; set; }
		TLBotInlineMessageBase SendMessage { get; set; }
	}
#endif

}