// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLBotCommand : ITLObject, TLBotCommand 
	{
		public String Command { get; set; }
		public String Description { get; set; }

		public ITLBotCommand() { }
		public ITLBotCommand(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.BotCommand; } }

		public override void Read(TLBinaryReader from)
		{
			Command = from.ReadString();
			Description = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC27AC8C7);
			to.Write(Command);
			to.Write(Description);
		}
	}

#if !PORTABLE
	[Guid(0x502d721c, 0x8d5d, 0x4f01, 0xe2, 0x0c, 0x23, 0x40, 0xd6, 0x6f, 0xdd, 0x7c)]
	public partial interface TLBotCommand : TLObject
	{
		String Command { get; set; }
		String Description { get; set; }
	}
#endif

}