// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLBotInlineMessageBase : TLObject, ITLBotInlineMessageBase
	{
		public TLReplyMarkupBase ReplyMarkup { get; set; }
	}

	[Guid(0xaaeaed91, 0xa5b1, 0x94ae, 0xb9, 0x7c, 0x74, 0xcc, 0x41, 0xb3, 0xaf, 0x8a)]
	public partial interface ITLBotInlineMessageBase : TLObject
	{
		TLReplyMarkupBase ReplyMarkup { get; set; }
	}
}