// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChannelParticipantCreator : ITLChannelParticipantBase, TLChannelParticipantCreator 
	{
		public ITLChannelParticipantCreator() { }
		public ITLChannelParticipantCreator(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelParticipantCreator; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE3E2E1F9);
			to.Write(UserId);
		}
	}

#if !PORTABLE
	[Guid(0x0a4b7259, 0xf48f, 0xfac2, 0xb0, 0x1a, 0x26, 0x54, 0x83, 0xa6, 0x8c, 0xc8)]
	public partial interface TLChannelParticipantCreator : TLChannelParticipantBase
	{
		Int32 UserId { get; set; }
	}
#endif

}