// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLChannelMessagesFilterBase : TLObject, ITLChannelMessagesFilterBase
	{
	}

	[Guid(0xd1ec2232, 0x6918, 0xe69d, 0xa8, 0x87, 0xf4, 0x58, 0x29, 0xf0, 0x5b, 0xc0)]
	public partial interface ITLChannelMessagesFilterBase : TLObject
	{
	}
}