// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChatParticipants : ITLChatParticipantsBase, TLChatParticipants 
	{
		public TLVector<TLChatParticipantBase> Participants { get; set; }
		public Int32 Version { get; set; }

		public ITLChatParticipants() { }
		public ITLChatParticipants(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChatParticipants; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
			Participants = TLFactory.Read<TLVector<TLChatParticipantBase>>(from);
			Version = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3F460FED);
			to.Write(ChatId);
			to.WriteObject(Participants);
			to.Write(Version);
		}
	}

#if !PORTABLE
	[Guid(0x90514981, 0x8455, 0x2ee0, 0xe4, 0x06, 0x26, 0x7a, 0x82, 0xaf, 0x58, 0xbe)]
	public partial interface TLChatParticipants : TLChatParticipantsBase
	{
		Int32 ChatId { get; set; }
		TLVector<TLChatParticipantBase> Participants { get; set; }
		Int32 Version { get; set; }
	}
#endif

}