// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLChannelParticipantsFilterBase : TLObject, ITLChannelParticipantsFilterBase
	{
	}

	[Guid(0xc9ad4282, 0x5af9, 0x0ab8, 0x0d, 0x79, 0xc9, 0x55, 0x60, 0xff, 0xc8, 0x0c)]
	public partial interface ITLChannelParticipantsFilterBase : TLObject
	{
	}
}