// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChatEmpty : ITLChatBase, TLChatEmpty 
	{
		public ITLChatEmpty() { }
		public ITLChatEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChatEmpty; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9BA2D800);
			to.Write(Id);
		}
	}

#if !PORTABLE
	[Guid(0xebf38aaa, 0x48e1, 0xa731, 0xcd, 0x1b, 0x6d, 0x13, 0x83, 0xa0, 0x37, 0x55)]
	public partial interface TLChatEmpty : TLChatBase
	{
		Int32 Id { get; set; }
	}
#endif

}