// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChannelsChannelParticipant : ITLObject, TLChannelsChannelParticipant 
	{
		public TLChannelParticipantBase Participant { get; set; }
		public TLVector<TLUserBase> Users { get; set; }

		public ITLChannelsChannelParticipant() { }
		public ITLChannelsChannelParticipant(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelsChannelParticipant; } }

		public override void Read(TLBinaryReader from)
		{
			Participant = TLFactory.Read<TLChannelParticipantBase>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xD0D9B163);
			to.WriteObject(Participant);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0x2fa0c252, 0x9201, 0x216c, 0xf5, 0x91, 0x0a, 0x18, 0x21, 0xbb, 0xb1, 0xb6)]
	public partial interface TLChannelsChannelParticipant : TLObject
	{
		TLChannelParticipantBase Participant { get; set; }
		TLVector<TLUserBase> Users { get; set; }
	}
#endif

}