// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLChatParticipantsBase : TLObject, ITLChatParticipantsBase
	{
		public Int32 ChatId { get; set; }
	}

	[Guid(0x90514981, 0x8455, 0x2ee0, 0xe4, 0x06, 0x26, 0x7a, 0x82, 0xaf, 0x58, 0xbe)]
	public partial interface ITLChatParticipantsBase : TLObject
	{
		Int32 ChatId { get; set; }
	}
}