// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChannelParticipant : ITLChannelParticipantBase, TLChannelParticipant 
	{
		public Int32 Date { get; set; }

		public ITLChannelParticipant() { }
		public ITLChannelParticipant(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelParticipant; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
			Date = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x15EBAC1D);
			to.Write(UserId);
			to.Write(Date);
		}
	}

#if !PORTABLE
	[Guid(0x0a4b7259, 0xf48f, 0xfac2, 0xb0, 0x1a, 0x26, 0x54, 0x83, 0xa6, 0x8c, 0xc8)]
	public partial interface TLChannelParticipant : TLChannelParticipantBase
	{
		Int32 UserId { get; set; }
		Int32 Date { get; set; }
	}
#endif

}