// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
	#else
	public
#endif
	abstract partial class ITLChannelParticipantsFilterBase : ITLObject, TLChannelParticipantsFilterBase
	{
	}

#if !PORTABLE
	[Guid(0xc9ad4282, 0x5af9, 0x0ab8, 0x0d, 0x79, 0xc9, 0x55, 0x60, 0xff, 0xc8, 0x0c)]
	public partial interface TLChannelParticipantsFilterBase : TLObject
	{
	}
#endif

}