// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsImportedContacts : ITLObject, TLContactsImportedContacts 
	{
		public TLVector<TLImportedContact> Imported { get; set; }
		public TLVector<Int64> RetryContacts { get; set; }
		public TLVector<TLUserBase> Users { get; set; }

		public ITLContactsImportedContacts() { }
		public ITLContactsImportedContacts(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsImportedContacts; } }

		public override void Read(TLBinaryReader from)
		{
			Imported = TLFactory.Read<TLVector<TLImportedContact>>(from);
			RetryContacts = TLFactory.Read<TLVector<Int64>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xAD524315);
			to.WriteObject(Imported);
			to.WriteObject(RetryContacts);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0xb7b7e4df, 0x51f8, 0x5067, 0x01, 0x8f, 0x0b, 0xd4, 0xe7, 0xb8, 0x06, 0xb3)]
	public partial interface TLContactsImportedContacts : TLObject
	{
		TLVector<TLImportedContact> Imported { get; set; }
		TLVector<Int64> RetryContacts { get; set; }
		TLVector<TLUserBase> Users { get; set; }
	}
#endif

}