// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsContacts : ITLContactsContactsBase, TLContactsContacts 
	{
		public TLVector<TLContact> Contacts { get; set; }
		public TLVector<TLUserBase> Users { get; set; }

		public ITLContactsContacts() { }
		public ITLContactsContacts(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsContacts; } }

		public override void Read(TLBinaryReader from)
		{
			Contacts = TLFactory.Read<TLVector<TLContact>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x6F8B8CB2);
			to.WriteObject(Contacts);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0xf1bc53e6, 0xd11a, 0xb62b, 0x31, 0x2c, 0xb5, 0x94, 0x2c, 0x34, 0xa9, 0xcc)]
	public partial interface TLContactsContacts : TLContactsContactsBase
	{
		TLVector<TLContact> Contacts { get; set; }
		TLVector<TLUserBase> Users { get; set; }
	}
#endif

}