// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsTopPeers : ITLContactsTopPeersBase, TLContactsTopPeers 
	{
		public TLVector<TLTopPeerCategoryPeers> Categories { get; set; }
		public TLVector<TLChatBase> Chats { get; set; }
		public TLVector<TLUserBase> Users { get; set; }

		public ITLContactsTopPeers() { }
		public ITLContactsTopPeers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsTopPeers; } }

		public override void Read(TLBinaryReader from)
		{
			Categories = TLFactory.Read<TLVector<TLTopPeerCategoryPeers>>(from);
			Chats = TLFactory.Read<TLVector<TLChatBase>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x70B772A8);
			to.WriteObject(Categories);
			to.WriteObject(Chats);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0x248b1a23, 0x281a, 0x78d9, 0xbe, 0x6e, 0x7d, 0x44, 0xd5, 0x8c, 0x28, 0x43)]
	public partial interface TLContactsTopPeers : TLContactsTopPeersBase
	{
		TLVector<TLTopPeerCategoryPeers> Categories { get; set; }
		TLVector<TLChatBase> Chats { get; set; }
		TLVector<TLUserBase> Users { get; set; }
	}
#endif

}