// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsBlocked : ITLContactsBlockedBase, TLContactsBlocked 
	{
		public ITLContactsBlocked() { }
		public ITLContactsBlocked(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsBlocked; } }

		public override void Read(TLBinaryReader from)
		{
			Blocked = TLFactory.Read<TLVector<TLContactBlocked>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x1C138D15);
			to.WriteObject(Blocked);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0x8dfb760e, 0x3780, 0x8ccc, 0xd7, 0x9c, 0x22, 0x98, 0x11, 0xd9, 0x35, 0x7f)]
	public partial interface TLContactsBlocked : TLContactsBlockedBase
	{
		TLVector<TLContactBlocked> Blocked { get; set; }
		TLVector<TLUserBase> Users { get; set; }
	}
#endif

}