// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLContactsTopPeersBase : TLObject, ITLContactsTopPeersBase
	{
	}

	[Guid(0x248b1a23, 0x281a, 0x78d9, 0xbe, 0x6e, 0x7d, 0x44, 0xd5, 0x8c, 0x28, 0x43)]
	public partial interface ITLContactsTopPeersBase : TLObject
	{
	}
}