// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactLinkHasPhone : ITLContactLinkBase, TLContactLinkHasPhone 
	{
		public ITLContactLinkHasPhone() { }
		public ITLContactLinkHasPhone(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactLinkHasPhone; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x268F3F59);
		}
	}

#if !PORTABLE
	[Guid(0x54a2d676, 0xf4ae, 0xf6c9, 0x3d, 0xca, 0x26, 0xd5, 0x41, 0x4d, 0x29, 0x5b)]
	public partial interface TLContactLinkHasPhone : TLContactLinkBase
	{
	}
#endif

}