// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContactsLink : ITLObject, TLContactsLink 
	{
		public TLContactLinkBase MyLink { get; set; }
		public TLContactLinkBase ForeignLink { get; set; }
		public TLUserBase User { get; set; }

		public ITLContactsLink() { }
		public ITLContactsLink(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContactsLink; } }

		public override void Read(TLBinaryReader from)
		{
			MyLink = TLFactory.Read<TLContactLinkBase>(from);
			ForeignLink = TLFactory.Read<TLContactLinkBase>(from);
			User = TLFactory.Read<TLUserBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3ACE484C);
			to.WriteObject(MyLink);
			to.WriteObject(ForeignLink);
			to.WriteObject(User);
		}
	}

#if !PORTABLE
	[Guid(0xd65874ff, 0x0353, 0x9504, 0xe9, 0x0a, 0x7d, 0xf8, 0x47, 0x2f, 0xd2, 0xd3)]
	public partial interface TLContactsLink : TLObject
	{
		TLContactLinkBase MyLink { get; set; }
		TLContactLinkBase ForeignLink { get; set; }
		TLUserBase User { get; set; }
	}
#endif

}