// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLDestroySessionOk : ITLDestroySessionResBase, TLDestroySessionOk 
	{
		public ITLDestroySessionOk() { }
		public ITLDestroySessionOk(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.DestroySessionOk; } }

		public override void Read(TLBinaryReader from)
		{
			SessionId = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE22045FC);
			to.Write(SessionId);
		}
	}

#if !PORTABLE
	[Guid(0x8dfc49cb, 0xcc18, 0xfa05, 0x56, 0xa6, 0x36, 0x04, 0x49, 0x90, 0xc5, 0x4d)]
	public partial interface TLDestroySessionOk : TLDestroySessionResBase
	{
		Int64 SessionId { get; set; }
	}
#endif

}