// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLDisabledFeature : ITLObject, TLDisabledFeature 
	{
		public String Feature { get; set; }
		public String Description { get; set; }

		public ITLDisabledFeature() { }
		public ITLDisabledFeature(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.DisabledFeature; } }

		public override void Read(TLBinaryReader from)
		{
			Feature = from.ReadString();
			Description = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xAE636F24);
			to.Write(Feature);
			to.Write(Description);
		}
	}

#if !PORTABLE
	[Guid(0x9accbd23, 0x8121, 0xcef7, 0xdf, 0x56, 0x3f, 0xa5, 0x08, 0x8b, 0xca, 0xd2)]
	public partial interface TLDisabledFeature : TLObject
	{
		String Feature { get; set; }
		String Description { get; set; }
	}
#endif

}