// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLDocumentAttributeAnimated : ITLDocumentAttributeBase, TLDocumentAttributeAnimated 
	{
		public ITLDocumentAttributeAnimated() { }
		public ITLDocumentAttributeAnimated(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.DocumentAttributeAnimated; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x11B58939);
		}
	}

#if !PORTABLE
	[Guid(0xf83854a2, 0xd82b, 0x0277, 0x53, 0x06, 0x42, 0x2d, 0x19, 0x01, 0x4b, 0xf8)]
	public partial interface TLDocumentAttributeAnimated : TLDocumentAttributeBase
	{
	}
#endif

}