// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLDraftMessageEmpty : ITLDraftMessageBase, TLDraftMessageEmpty 
	{
		public ITLDraftMessageEmpty() { }
		public ITLDraftMessageEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.DraftMessageEmpty; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xBA4BAEC5);
		}
	}

#if !PORTABLE
	[Guid(0x1173d1f1, 0x0ae8, 0xa890, 0x7e, 0x52, 0xc3, 0xab, 0xff, 0x2f, 0xea, 0x87)]
	public partial interface TLDraftMessageEmpty : TLDraftMessageBase
	{
	}
#endif

}