// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLDraftMessageBase : TLObject, ITLDraftMessageBase
	{
	}

	[Guid(0x1173d1f1, 0x0ae8, 0xa890, 0x7e, 0x52, 0xc3, 0xab, 0xff, 0x2f, 0xea, 0x87)]
	public partial interface ITLDraftMessageBase : TLObject
	{
	}
}