// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLEncryptedFileEmpty : ITLEncryptedFileBase, TLEncryptedFileEmpty 
	{
		public ITLEncryptedFileEmpty() { }
		public ITLEncryptedFileEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.EncryptedFileEmpty; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC21F497E);
		}
	}

#if !PORTABLE
	[Guid(0x2231601b, 0xd763, 0x24cd, 0x34, 0x80, 0x71, 0xa6, 0x54, 0x85, 0xde, 0x02)]
	public partial interface TLEncryptedFileEmpty : TLEncryptedFileBase
	{
	}
#endif

}