// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLFoundGifCached : ITLFoundGifBase, TLFoundGifCached 
	{
		public TLPhotoBase Photo { get; set; }
		public TLDocumentBase Document { get; set; }

		public ITLFoundGifCached() { }
		public ITLFoundGifCached(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.FoundGifCached; } }

		public override void Read(TLBinaryReader from)
		{
			Url = from.ReadString();
			Photo = TLFactory.Read<TLPhotoBase>(from);
			Document = TLFactory.Read<TLDocumentBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9C750409);
			to.Write(Url);
			to.WriteObject(Photo);
			to.WriteObject(Document);
		}
	}

#if !PORTABLE
	[Guid(0xc8125449, 0x9689, 0x11ca, 0x95, 0x48, 0x1f, 0x26, 0x2a, 0x52, 0xb4, 0x68)]
	public partial interface TLFoundGifCached : TLFoundGifBase
	{
		String Url { get; set; }
		TLPhotoBase Photo { get; set; }
		TLDocumentBase Document { get; set; }
	}
#endif

}