// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLGeoPoint : ITLGeoPointBase, TLGeoPoint 
	{
		public Double Long { get; set; }
		public Double Lat { get; set; }

		public ITLGeoPoint() { }
		public ITLGeoPoint(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.GeoPoint; } }

		public override void Read(TLBinaryReader from)
		{
			Long = from.ReadDouble();
			Lat = from.ReadDouble();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x2049D70C);
			to.Write(Long);
			to.Write(Lat);
		}
	}

#if !PORTABLE
	[Guid(0x177b0af4, 0x2620, 0xbdbb, 0xe5, 0xa0, 0xf3, 0x70, 0x58, 0x9a, 0xcf, 0xb7)]
	public partial interface TLGeoPoint : TLGeoPointBase
	{
		Double Long { get; set; }
		Double Lat { get; set; }
	}
#endif

}