// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHelpTermsOfService : ITLObject, TLHelpTermsOfService 
	{
		public String Text { get; set; }

		public ITLHelpTermsOfService() { }
		public ITLHelpTermsOfService(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpTermsOfService; } }

		public override void Read(TLBinaryReader from)
		{
			Text = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF1EE3E90);
			to.Write(Text);
		}
	}

#if !PORTABLE
	[Guid(0x2dadfd95, 0x0b35, 0xf6e0, 0x89, 0x88, 0x82, 0x18, 0xf0, 0x31, 0x8b, 0xd8)]
	public partial interface TLHelpTermsOfService : TLObject
	{
		String Text { get; set; }
	}
#endif

}