// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHelpSupport : ITLObject, TLHelpSupport 
	{
		public String PhoneNumber { get; set; }
		public TLUserBase User { get; set; }

		public ITLHelpSupport() { }
		public ITLHelpSupport(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HelpSupport; } }

		public override void Read(TLBinaryReader from)
		{
			PhoneNumber = from.ReadString();
			User = TLFactory.Read<TLUserBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x17C6B5F6);
			to.Write(PhoneNumber);
			to.WriteObject(User);
		}
	}

#if !PORTABLE
	[Guid(0x2735e94d, 0xe0a7, 0x72c0, 0x40, 0x76, 0x7a, 0xe0, 0x4f, 0x35, 0x7f, 0xb1)]
	public partial interface TLHelpSupport : TLObject
	{
		String PhoneNumber { get; set; }
		TLUserBase User { get; set; }
	}
#endif

}