// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLHighScore : ITLObject, TLHighScore 
	{
		public Int32 Pos { get; set; }
		public Int32 UserId { get; set; }
		public Int32 Score { get; set; }

		public ITLHighScore() { }
		public ITLHighScore(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.HighScore; } }

		public override void Read(TLBinaryReader from)
		{
			Pos = from.ReadInt32();
			UserId = from.ReadInt32();
			Score = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x58FFFCD0);
			to.Write(Pos);
			to.Write(UserId);
			to.Write(Score);
		}
	}

#if !PORTABLE
	[Guid(0xe7e9e0b1, 0xe133, 0x5968, 0x06, 0xee, 0x11, 0x15, 0xb6, 0x0b, 0xc5, 0x69)]
	public partial interface TLHighScore : TLObject
	{
		Int32 Pos { get; set; }
		Int32 UserId { get; set; }
		Int32 Score { get; set; }
	}
#endif

}