// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLImportedContact : ITLObject, TLImportedContact 
	{
		public Int32 UserId { get; set; }
		public Int64 ClientId { get; set; }

		public ITLImportedContact() { }
		public ITLImportedContact(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ImportedContact; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
			ClientId = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xD0028438);
			to.Write(UserId);
			to.Write(ClientId);
		}
	}

#if !PORTABLE
	[Guid(0xaa669f91, 0xc06c, 0x1ada, 0x73, 0x99, 0xbe, 0x8b, 0xf8, 0xd2, 0x35, 0x08)]
	public partial interface TLImportedContact : TLObject
	{
		Int32 UserId { get; set; }
		Int64 ClientId { get; set; }
	}
#endif

}