// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputNotifyUsers : ITLInputNotifyPeerBase, TLInputNotifyUsers 
	{
		public ITLInputNotifyUsers() { }
		public ITLInputNotifyUsers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputNotifyUsers; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x193B4417);
		}
	}

#if !PORTABLE
	[Guid(0x77a24f4a, 0x9b72, 0x8f4b, 0x36, 0xba, 0x27, 0x88, 0x44, 0xdd, 0x8d, 0x43)]
	public partial interface TLInputNotifyUsers : TLInputNotifyPeerBase
	{
	}
#endif

}