// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputDocument : ITLInputDocumentBase, TLInputDocument 
	{
		public Int64 Id { get; set; }
		public Int64 AccessHash { get; set; }

		public ITLInputDocument() { }
		public ITLInputDocument(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputDocument; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt64();
			AccessHash = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x18798952);
			to.Write(Id);
			to.Write(AccessHash);
		}
	}

#if !PORTABLE
	[Guid(0x1fe42ff2, 0xd966, 0x5220, 0x2a, 0xac, 0x46, 0x33, 0x18, 0x30, 0xbc, 0xb9)]
	public partial interface TLInputDocument : TLInputDocumentBase
	{
		Int64 Id { get; set; }
		Int64 AccessHash { get; set; }
	}
#endif

}