// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputStickeredMediaPhoto : ITLInputStickeredMediaBase, TLInputStickeredMediaPhoto 
	{
		public TLInputPhotoBase Id { get; set; }

		public ITLInputStickeredMediaPhoto() { }
		public ITLInputStickeredMediaPhoto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputStickeredMediaPhoto; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLInputPhotoBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4A992157);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0xcf0fecc1, 0xa6f6, 0xb13f, 0xe6, 0xa3, 0x75, 0xd6, 0x32, 0x8c, 0x79, 0x77)]
	public partial interface TLInputStickeredMediaPhoto : TLInputStickeredMediaBase
	{
		TLInputPhotoBase Id { get; set; }
	}
#endif

}