// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputBotInlineMessageMediaAuto : ITLInputBotInlineMessageBase, TLInputBotInlineMessageMediaAuto, ITLMessageMediaCaption 
	{
		public bool HasReplyMarkup { get { return Flags.HasFlag(TLInputBotInlineMessageMediaAutoFlag.ReplyMarkup); } set { Flags = value ? (Flags | TLInputBotInlineMessageMediaAutoFlag.ReplyMarkup) : (Flags & ~TLInputBotInlineMessageMediaAutoFlag.ReplyMarkup); } }

		public TLInputBotInlineMessageMediaAutoFlag Flags { get; set; }
		public String Caption { get; set; }

		public ITLInputBotInlineMessageMediaAuto() { }
		public ITLInputBotInlineMessageMediaAuto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputBotInlineMessageMediaAuto; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLInputBotInlineMessageMediaAutoFlag)from.ReadInt32();
			Caption = from.ReadString();
			if (HasReplyMarkup) ReplyMarkup = TLFactory.Read<TLReplyMarkupBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			UpdateFlags();

			to.Write(0x292FED13);
			to.Write((Int32)Flags);
			to.Write(Caption);
			if (HasReplyMarkup) to.WriteObject(ReplyMarkup);
		}

		private void UpdateFlags()
		{
			HasReplyMarkup = ReplyMarkup != null;
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLInputBotInlineMessageMediaAutoFlag : Int32
	{
		ReplyMarkup = (1 << 2),
	}
#endif

#if !PORTABLE
	[Guid(0xdd9053ca, 0xf83c, 0xaafa, 0x47, 0x35, 0xce, 0x04, 0x7d, 0x2e, 0x53, 0x17)]
	public partial interface TLInputBotInlineMessageMediaAuto : TLInputBotInlineMessageBase
	{
		bool HasReplyMarkup { get; set; }

		TLInputBotInlineMessageMediaAutoFlag Flags { get; set; }
		String Caption { get; set; }
		TLReplyMarkupBase ReplyMarkup { get; set; }
	}
#endif

}