// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputChatPhoto : ITLInputChatPhotoBase, TLInputChatPhoto 
	{
		public TLInputPhotoBase Id { get; set; }

		public ITLInputChatPhoto() { }
		public ITLInputChatPhoto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputChatPhoto; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLInputPhotoBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x8953AD37);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0x088150f5, 0x7a5b, 0x5cfd, 0xc2, 0x86, 0x87, 0x48, 0xe2, 0xd7, 0x30, 0xf9)]
	public partial interface TLInputChatPhoto : TLInputChatPhotoBase
	{
		TLInputPhotoBase Id { get; set; }
	}
#endif

}