// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputPaymentCredentialsSaved : ITLInputPaymentCredentialsBase, TLInputPaymentCredentialsSaved 
	{
		public String Id { get; set; }
		public Byte[] TmpPassword { get; set; }

		public ITLInputPaymentCredentialsSaved() { }
		public ITLInputPaymentCredentialsSaved(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputPaymentCredentialsSaved; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadString();
			TmpPassword = from.ReadByteArray();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC10EB2CF);
			to.Write(Id);
			to.WriteByteArray(TmpPassword);
		}
	}

#if !PORTABLE
	[Guid(0x559af88d, 0xd7a2, 0x8d93, 0xe4, 0x02, 0x16, 0xee, 0x38, 0xe2, 0xb1, 0x94)]
	public partial interface TLInputPaymentCredentialsSaved : TLInputPaymentCredentialsBase
	{
		String Id { get; set; }
		Byte[] TmpPassword { get; set; }
	}
#endif

}