// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputDocumentEmpty : ITLInputDocumentBase, TLInputDocumentEmpty 
	{
		public ITLInputDocumentEmpty() { }
		public ITLInputDocumentEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputDocumentEmpty; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x72F0EAAE);
		}
	}

#if !PORTABLE
	[Guid(0x1fe42ff2, 0xd966, 0x5220, 0x2a, 0xac, 0x46, 0x33, 0x18, 0x30, 0xbc, 0xb9)]
	public partial interface TLInputDocumentEmpty : TLInputDocumentBase
	{
	}
#endif

}