// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputNotifyChats : ITLInputNotifyPeerBase, TLInputNotifyChats 
	{
		public ITLInputNotifyChats() { }
		public ITLInputNotifyChats(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputNotifyChats; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4A95E84E);
		}
	}

#if !PORTABLE
	[Guid(0x77a24f4a, 0x9b72, 0x8f4b, 0x36, 0xba, 0x27, 0x88, 0x44, 0xdd, 0x8d, 0x43)]
	public partial interface TLInputNotifyChats : TLInputNotifyPeerBase
	{
	}
#endif

}