// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputPrivacyKeyPhoneCall : ITLInputPrivacyKeyBase, TLInputPrivacyKeyPhoneCall 
	{
		public ITLInputPrivacyKeyPhoneCall() { }
		public ITLInputPrivacyKeyPhoneCall(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputPrivacyKeyPhoneCall; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xFABADC5F);
		}
	}

#if !PORTABLE
	[Guid(0xd59c2c2c, 0x3e35, 0x4972, 0x35, 0x7b, 0x3f, 0xf8, 0xdd, 0x6e, 0x5a, 0xd8)]
	public partial interface TLInputPrivacyKeyPhoneCall : TLInputPrivacyKeyBase
	{
	}
#endif

}