// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputBotInlineResultGame : ITLInputBotInlineResultBase, TLInputBotInlineResultGame 
	{
		public String ShortName { get; set; }

		public ITLInputBotInlineResultGame() { }
		public ITLInputBotInlineResultGame(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputBotInlineResultGame; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadString();
			ShortName = from.ReadString();
			SendMessage = TLFactory.Read<TLInputBotInlineMessageBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4FA417F2);
			to.Write(Id);
			to.Write(ShortName);
			to.WriteObject(SendMessage);
		}
	}

#if !PORTABLE
	[Guid(0xe2885374, 0x6d32, 0x33fe, 0xf3, 0x8d, 0x2e, 0x5b, 0x2f, 0x0a, 0x68, 0x0e)]
	public partial interface TLInputBotInlineResultGame : TLInputBotInlineResultBase
	{
		String Id { get; set; }
		String ShortName { get; set; }
		TLInputBotInlineMessageBase SendMessage { get; set; }
	}
#endif

}