// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputMediaGame : ITLInputMediaBase, TLInputMediaGame 
	{
		public TLInputGameBase Id { get; set; }

		public ITLInputMediaGame() { }
		public ITLInputMediaGame(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputMediaGame; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLInputGameBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xD33F43F3);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0x1fd0d7a9, 0x0616, 0x23a7, 0x35, 0x1a, 0x30, 0x0e, 0x9d, 0xb7, 0xaf, 0x84)]
	public partial interface TLInputMediaGame : TLInputMediaBase
	{
		TLInputGameBase Id { get; set; }
	}
#endif

}