// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputStickerSetEmpty : ITLInputStickerSetBase, TLInputStickerSetEmpty 
	{
		public ITLInputStickerSetEmpty() { }
		public ITLInputStickerSetEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputStickerSetEmpty; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xFFB62B95);
		}
	}

#if !PORTABLE
	[Guid(0x0329de7e, 0x3c9a, 0x637e, 0x8a, 0x34, 0x21, 0xd5, 0xb4, 0x4f, 0x65, 0xed)]
	public partial interface TLInputStickerSetEmpty : TLInputStickerSetBase
	{
	}
#endif

}