// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLInputPhotoBase : TLObject, ITLInputPhotoBase
	{
	}

	[Guid(0xa7dfd0ba, 0x5fdb, 0x3fd1, 0xea, 0xd8, 0x2b, 0xe7, 0x16, 0x80, 0xe1, 0x80)]
	public partial interface ITLInputPhotoBase : TLObject
	{
	}
}