// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputBotInlineMessageMediaVenue : ITLInputBotInlineMessageBase, TLInputBotInlineMessageMediaVenue 
	{
		public bool HasReplyMarkup { get { return Flags.HasFlag(TLInputBotInlineMessageMediaVenueFlag.ReplyMarkup); } set { Flags = value ? (Flags | TLInputBotInlineMessageMediaVenueFlag.ReplyMarkup) : (Flags & ~TLInputBotInlineMessageMediaVenueFlag.ReplyMarkup); } }

		public TLInputBotInlineMessageMediaVenueFlag Flags { get; set; }
		public TLInputGeoPointBase GeoPoint { get; set; }
		public String Title { get; set; }
		public String Address { get; set; }
		public String Provider { get; set; }
		public String VenueId { get; set; }

		public ITLInputBotInlineMessageMediaVenue() { }
		public ITLInputBotInlineMessageMediaVenue(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputBotInlineMessageMediaVenue; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLInputBotInlineMessageMediaVenueFlag)from.ReadInt32();
			GeoPoint = TLFactory.Read<TLInputGeoPointBase>(from);
			Title = from.ReadString();
			Address = from.ReadString();
			Provider = from.ReadString();
			VenueId = from.ReadString();
			if (HasReplyMarkup) ReplyMarkup = TLFactory.Read<TLReplyMarkupBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			UpdateFlags();

			to.Write(0xAAAFADC8);
			to.Write((Int32)Flags);
			to.WriteObject(GeoPoint);
			to.Write(Title);
			to.Write(Address);
			to.Write(Provider);
			to.Write(VenueId);
			if (HasReplyMarkup) to.WriteObject(ReplyMarkup);
		}

		private void UpdateFlags()
		{
			HasReplyMarkup = ReplyMarkup != null;
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLInputBotInlineMessageMediaVenueFlag : Int32
	{
		ReplyMarkup = (1 << 2),
	}
#endif

#if !PORTABLE
	[Guid(0xdd9053ca, 0xf83c, 0xaafa, 0x47, 0x35, 0xce, 0x04, 0x7d, 0x2e, 0x53, 0x17)]
	public partial interface TLInputBotInlineMessageMediaVenue : TLInputBotInlineMessageBase
	{
		bool HasReplyMarkup { get; set; }

		TLInputBotInlineMessageMediaVenueFlag Flags { get; set; }
		TLInputGeoPointBase GeoPoint { get; set; }
		String Title { get; set; }
		String Address { get; set; }
		String Provider { get; set; }
		String VenueId { get; set; }
		TLReplyMarkupBase ReplyMarkup { get; set; }
	}
#endif

}