// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputPrivacyValueDisallowAll : ITLInputPrivacyRuleBase, TLInputPrivacyValueDisallowAll 
	{
		public ITLInputPrivacyValueDisallowAll() { }
		public ITLInputPrivacyValueDisallowAll(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputPrivacyValueDisallowAll; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xD66B66C9);
		}
	}

#if !PORTABLE
	[Guid(0x70106d70, 0x9348, 0xb60e, 0x91, 0xfa, 0xc4, 0xc0, 0x72, 0xc7, 0x35, 0x45)]
	public partial interface TLInputPrivacyValueDisallowAll : TLInputPrivacyRuleBase
	{
	}
#endif

}