// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputStickerSetID : ITLInputStickerSetBase, TLInputStickerSetID 
	{
		public Int64 Id { get; set; }
		public Int64 AccessHash { get; set; }

		public ITLInputStickerSetID() { }
		public ITLInputStickerSetID(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputStickerSetID; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt64();
			AccessHash = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9DE7A269);
			to.Write(Id);
			to.Write(AccessHash);
		}
	}

#if !PORTABLE
	[Guid(0x0329de7e, 0x3c9a, 0x637e, 0x8a, 0x34, 0x21, 0xd5, 0xb4, 0x4f, 0x65, 0xed)]
	public partial interface TLInputStickerSetID : TLInputStickerSetBase
	{
		Int64 Id { get; set; }
		Int64 AccessHash { get; set; }
	}
#endif

}