// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputPrivacyValueDisallowUsers : ITLInputPrivacyRuleBase, TLInputPrivacyValueDisallowUsers 
	{
		public TLVector<TLInputUserBase> Users { get; set; }

		public ITLInputPrivacyValueDisallowUsers() { }
		public ITLInputPrivacyValueDisallowUsers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputPrivacyValueDisallowUsers; } }

		public override void Read(TLBinaryReader from)
		{
			Users = TLFactory.Read<TLVector<TLInputUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x90110467);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0x70106d70, 0x9348, 0xb60e, 0x91, 0xfa, 0xc4, 0xc0, 0x72, 0xc7, 0x35, 0x45)]
	public partial interface TLInputPrivacyValueDisallowUsers : TLInputPrivacyRuleBase
	{
		TLVector<TLInputUserBase> Users { get; set; }
	}
#endif

}