// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputWebDocument : ITLObject, TLInputWebDocument 
	{
		public String Url { get; set; }
		public Int32 Size { get; set; }
		public String MimeType { get; set; }
		public TLVector<TLDocumentAttributeBase> Attributes { get; set; }

		public ITLInputWebDocument() { }
		public ITLInputWebDocument(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputWebDocument; } }

		public override void Read(TLBinaryReader from)
		{
			Url = from.ReadString();
			Size = from.ReadInt32();
			MimeType = from.ReadString();
			Attributes = TLFactory.Read<TLVector<TLDocumentAttributeBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9BED434D);
			to.Write(Url);
			to.Write(Size);
			to.Write(MimeType);
			to.WriteObject(Attributes);
		}
	}

#if !PORTABLE
	[Guid(0x33a85dd9, 0xaed8, 0x6714, 0x5b, 0x03, 0x10, 0x70, 0xe8, 0xe5, 0xfc, 0xb8)]
	public partial interface TLInputWebDocument : TLObject
	{
		String Url { get; set; }
		Int32 Size { get; set; }
		String MimeType { get; set; }
		TLVector<TLDocumentAttributeBase> Attributes { get; set; }
	}
#endif

}