// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputGameID : ITLInputGameBase, TLInputGameID 
	{
		public Int64 Id { get; set; }
		public Int64 AccessHash { get; set; }

		public ITLInputGameID() { }
		public ITLInputGameID(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputGameID; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt64();
			AccessHash = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x32C3E77);
			to.Write(Id);
			to.Write(AccessHash);
		}
	}

#if !PORTABLE
	[Guid(0xc106ada7, 0x934c, 0x26e4, 0x60, 0xd5, 0x72, 0xcf, 0x75, 0xe1, 0x00, 0xd7)]
	public partial interface TLInputGameID : TLInputGameBase
	{
		Int64 Id { get; set; }
		Int64 AccessHash { get; set; }
	}
#endif

}