// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputUser : ITLInputUserBase, TLInputUser 
	{
		public Int32 UserId { get; set; }
		public Int64 AccessHash { get; set; }

		public ITLInputUser() { }
		public ITLInputUser(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputUser; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
			AccessHash = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xD8292816);
			to.Write(UserId);
			to.Write(AccessHash);
		}
	}

#if !PORTABLE
	[Guid(0x4ea31f1a, 0x8950, 0xa34a, 0x45, 0xe7, 0x45, 0xc8, 0xe5, 0xe6, 0x0c, 0x33)]
	public partial interface TLInputUser : TLInputUserBase
	{
		Int32 UserId { get; set; }
		Int64 AccessHash { get; set; }
	}
#endif

}