// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputPhoneCall : ITLObject, TLInputPhoneCall 
	{
		public Int64 Id { get; set; }
		public Int64 AccessHash { get; set; }

		public ITLInputPhoneCall() { }
		public ITLInputPhoneCall(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputPhoneCall; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt64();
			AccessHash = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x1E36FDED);
			to.Write(Id);
			to.Write(AccessHash);
		}
	}

#if !PORTABLE
	[Guid(0x40549491, 0xc66a, 0xdfcd, 0xb4, 0x59, 0x95, 0x90, 0xa8, 0x83, 0xef, 0xb3)]
	public partial interface TLInputPhoneCall : TLObject
	{
		Int64 Id { get; set; }
		Int64 AccessHash { get; set; }
	}
#endif

}