// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputMediaPhotoExternal : ITLInputMediaBase, TLInputMediaPhotoExternal, ITLMessageMediaCaption 
	{
		public String Url { get; set; }
		public String Caption { get; set; }

		public ITLInputMediaPhotoExternal() { }
		public ITLInputMediaPhotoExternal(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputMediaPhotoExternal; } }

		public override void Read(TLBinaryReader from)
		{
			Url = from.ReadString();
			Caption = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB55F4F18);
			to.Write(Url);
			to.Write(Caption);
		}
	}

#if !PORTABLE
	[Guid(0x1fd0d7a9, 0x0616, 0x23a7, 0x35, 0x1a, 0x30, 0x0e, 0x9d, 0xb7, 0xaf, 0x84)]
	public partial interface TLInputMediaPhotoExternal : TLInputMediaBase
	{
		String Url { get; set; }
		String Caption { get; set; }
	}
#endif

}