// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputPeerNotifyEventsEmpty : ITLInputPeerNotifyEventsBase, TLInputPeerNotifyEventsEmpty 
	{
		public ITLInputPeerNotifyEventsEmpty() { }
		public ITLInputPeerNotifyEventsEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputPeerNotifyEventsEmpty; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF03064D8);
		}
	}

#if !PORTABLE
	[Guid(0xd0abdfbe, 0x7113, 0x4db9, 0xda, 0xd5, 0xac, 0x4d, 0x9d, 0xff, 0x7c, 0xf2)]
	public partial interface TLInputPeerNotifyEventsEmpty : TLInputPeerNotifyEventsBase
	{
	}
#endif

}