// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputGeoPoint : ITLInputGeoPointBase, TLInputGeoPoint 
	{
		public Double Lat { get; set; }
		public Double Long { get; set; }

		public ITLInputGeoPoint() { }
		public ITLInputGeoPoint(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputGeoPoint; } }

		public override void Read(TLBinaryReader from)
		{
			Lat = from.ReadDouble();
			Long = from.ReadDouble();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF3B7ACC9);
			to.Write(Lat);
			to.Write(Long);
		}
	}

#if !PORTABLE
	[Guid(0x5ae257d5, 0x82a9, 0xf312, 0x00, 0x0d, 0xf8, 0x86, 0xf4, 0xb6, 0xe1, 0x7f)]
	public partial interface TLInputGeoPoint : TLInputGeoPointBase
	{
		Double Lat { get; set; }
		Double Long { get; set; }
	}
#endif

}