// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputMediaDocument : ITLInputMediaBase, TLInputMediaDocument, ITLMessageMediaCaption 
	{
		public TLInputDocumentBase Id { get; set; }
		public String Caption { get; set; }

		public ITLInputMediaDocument() { }
		public ITLInputMediaDocument(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputMediaDocument; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLInputDocumentBase>(from);
			Caption = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x1A77F29C);
			to.WriteObject(Id);
			to.Write(Caption);
		}
	}

#if !PORTABLE
	[Guid(0x1fd0d7a9, 0x0616, 0x23a7, 0x35, 0x1a, 0x30, 0x0e, 0x9d, 0xb7, 0xaf, 0x84)]
	public partial interface TLInputMediaDocument : TLInputMediaBase
	{
		TLInputDocumentBase Id { get; set; }
		String Caption { get; set; }
	}
#endif

}