// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputPhoneContact : ITLInputContactBase, TLInputPhoneContact 
	{
		public Int64 ClientId { get; set; }
		public String Phone { get; set; }
		public String FirstName { get; set; }
		public String LastName { get; set; }

		public ITLInputPhoneContact() { }
		public ITLInputPhoneContact(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputPhoneContact; } }

		public override void Read(TLBinaryReader from)
		{
			ClientId = from.ReadInt64();
			Phone = from.ReadString();
			FirstName = from.ReadString();
			LastName = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF392B7F4);
			to.Write(ClientId);
			to.Write(Phone);
			to.Write(FirstName);
			to.Write(LastName);
		}
	}

#if !PORTABLE
	[Guid(0x29fd10ac, 0x956e, 0xfa45, 0xb0, 0xe2, 0xcb, 0x93, 0xdd, 0x5c, 0x2a, 0xe1)]
	public partial interface TLInputPhoneContact : TLInputContactBase
	{
		Int64 ClientId { get; set; }
		String Phone { get; set; }
		String FirstName { get; set; }
		String LastName { get; set; }
	}
#endif

}