// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputFileBig : ITLInputFileBase, TLInputFileBig 
	{
		public ITLInputFileBig() { }
		public ITLInputFileBig(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputFileBig; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt64();
			Parts = from.ReadInt32();
			Name = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xFA4F0BB5);
			to.Write(Id);
			to.Write(Parts);
			to.Write(Name);
		}
	}

#if !PORTABLE
	[Guid(0x43f99e29, 0xc7a1, 0x755a, 0xb2, 0xfc, 0x0f, 0x67, 0x1d, 0xec, 0x8c, 0x52)]
	public partial interface TLInputFileBig : TLInputFileBase
	{
		Int64 Id { get; set; }
		Int32 Parts { get; set; }
		String Name { get; set; }
	}
#endif

}