// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLInputFileLocationBase : TLObject, ITLInputFileLocationBase
	{
	}

	[Guid(0xc4ea377a, 0x995b, 0x50c3, 0x03, 0x35, 0x99, 0x43, 0x26, 0xe6, 0xff, 0x59)]
	public partial interface ITLInputFileLocationBase : TLObject
	{
	}
}