// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLInputGeoPointEmpty : ITLInputGeoPointBase, TLInputGeoPointEmpty 
	{
		public ITLInputGeoPointEmpty() { }
		public ITLInputGeoPointEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.InputGeoPointEmpty; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE4C123D6);
		}
	}

#if !PORTABLE
	[Guid(0x5ae257d5, 0x82a9, 0xf312, 0x00, 0x0d, 0xf8, 0x86, 0xf4, 0xb6, 0xe1, 0x7f)]
	public partial interface TLInputGeoPointEmpty : TLInputGeoPointBase
	{
	}
#endif

}