// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLInputNotifyPeerBase : TLObject, ITLInputNotifyPeerBase
	{
	}

	[Guid(0x77a24f4a, 0x9b72, 0x8f4b, 0x36, 0xba, 0x27, 0x88, 0x44, 0xdd, 0x8d, 0x43)]
	public partial interface ITLInputNotifyPeerBase : TLObject
	{
	}
}