// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLKeyboardButtonCallback : ITLKeyboardButtonBase, TLKeyboardButtonCallback 
	{
		public Byte[] Data { get; set; }

		public ITLKeyboardButtonCallback() { }
		public ITLKeyboardButtonCallback(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.KeyboardButtonCallback; } }

		public override void Read(TLBinaryReader from)
		{
			Text = from.ReadString();
			Data = from.ReadByteArray();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x683A5E46);
			to.Write(Text);
			to.WriteByteArray(Data);
		}
	}

#if !PORTABLE
	[Guid(0x64b95636, 0x2de1, 0xcca8, 0xa8, 0xe8, 0xf3, 0xfa, 0x81, 0xc2, 0xe4, 0x8f)]
	public partial interface TLKeyboardButtonCallback : TLKeyboardButtonBase
	{
		String Text { get; set; }
		Byte[] Data { get; set; }
	}
#endif

}