// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLKeyboardButtonRequestPhone : ITLKeyboardButtonBase, TLKeyboardButtonRequestPhone 
	{
		public ITLKeyboardButtonRequestPhone() { }
		public ITLKeyboardButtonRequestPhone(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.KeyboardButtonRequestPhone; } }

		public override void Read(TLBinaryReader from)
		{
			Text = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB16A6C29);
			to.Write(Text);
		}
	}

#if !PORTABLE
	[Guid(0x64b95636, 0x2de1, 0xcca8, 0xa8, 0xe8, 0xf3, 0xfa, 0x81, 0xc2, 0xe4, 0x8f)]
	public partial interface TLKeyboardButtonRequestPhone : TLKeyboardButtonBase
	{
		String Text { get; set; }
	}
#endif

}