// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLLabeledPrice : ITLObject, TLLabeledPrice 
	{
		public String Label { get; set; }
		public Int64 Amount { get; set; }

		public ITLLabeledPrice() { }
		public ITLLabeledPrice(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.LabeledPrice; } }

		public override void Read(TLBinaryReader from)
		{
			Label = from.ReadString();
			Amount = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xCB296BF8);
			to.Write(Label);
			to.Write(Amount);
		}
	}

#if !PORTABLE
	[Guid(0x0adb4347, 0xb98b, 0x7b44, 0x81, 0x77, 0xab, 0xc7, 0x3f, 0x0d, 0x0e, 0x19)]
	public partial interface TLLabeledPrice : TLObject
	{
		String Label { get; set; }
		Int64 Amount { get; set; }
	}
#endif

}