// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesSentEncryptedMessage : ITLMessagesSentEncryptedMessageBase, TLMessagesSentEncryptedMessage 
	{
		public ITLMessagesSentEncryptedMessage() { }
		public ITLMessagesSentEncryptedMessage(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesSentEncryptedMessage; } }

		public override void Read(TLBinaryReader from)
		{
			Date = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x560F8935);
			to.Write(Date);
		}
	}

#if !PORTABLE
	[Guid(0x52738c6c, 0x5a5a, 0xe520, 0xc5, 0x94, 0x46, 0x4d, 0xc3, 0x11, 0x0e, 0x18)]
	public partial interface TLMessagesSentEncryptedMessage : TLMessagesSentEncryptedMessageBase
	{
		Int32 Date { get; set; }
	}
#endif

}