// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessageActionPaymentSent : ITLMessageActionBase, TLMessageActionPaymentSent 
	{
		public String Currency { get; set; }
		public Int64 TotalAmount { get; set; }

		public ITLMessageActionPaymentSent() { }
		public ITLMessageActionPaymentSent(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessageActionPaymentSent; } }

		public override void Read(TLBinaryReader from)
		{
			Currency = from.ReadString();
			TotalAmount = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x40699CD0);
			to.Write(Currency);
			to.Write(TotalAmount);
		}
	}

#if !PORTABLE
	[Guid(0xb7ad6125, 0xe49b, 0x6bc2, 0x5b, 0x0d, 0x45, 0x94, 0xee, 0x69, 0x89, 0x21)]
	public partial interface TLMessageActionPaymentSent : TLMessageActionBase
	{
		String Currency { get; set; }
		Int64 TotalAmount { get; set; }
	}
#endif

}