// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessageMediaPhoto : ITLMessageMediaBase, TLMessageMediaPhoto, ITLMessageMediaCaption 
	{
		public TLPhotoBase Photo { get; set; }
		public String Caption { get; set; }

		public ITLMessageMediaPhoto() { }
		public ITLMessageMediaPhoto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessageMediaPhoto; } }

		public override void Read(TLBinaryReader from)
		{
			Photo = TLFactory.Read<TLPhotoBase>(from);
			Caption = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3D8CE53D);
			to.WriteObject(Photo);
			to.Write(Caption);
		}
	}

#if !PORTABLE
	[Guid(0xc59dc1cb, 0xf129, 0xf361, 0xcc, 0x4f, 0x3e, 0xaa, 0x83, 0x64, 0x9d, 0xe7)]
	public partial interface TLMessageMediaPhoto : TLMessageMediaBase
	{
		TLPhotoBase Photo { get; set; }
		String Caption { get; set; }
	}
#endif

}