// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesChatsSlice : ITLMessagesChatsBase, TLMessagesChatsSlice 
	{
		public Int32 Count { get; set; }

		public ITLMessagesChatsSlice() { }
		public ITLMessagesChatsSlice(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesChatsSlice; } }

		public override void Read(TLBinaryReader from)
		{
			Count = from.ReadInt32();
			Chats = TLFactory.Read<TLVector<TLChatBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9CD81144);
			to.Write(Count);
			to.WriteObject(Chats);
		}
	}

#if !PORTABLE
	[Guid(0x4e5ee45d, 0x229b, 0x942f, 0x5e, 0x54, 0xa7, 0xaa, 0x85, 0x07, 0x70, 0xf8)]
	public partial interface TLMessagesChatsSlice : TLMessagesChatsBase
	{
		Int32 Count { get; set; }
		TLVector<TLChatBase> Chats { get; set; }
	}
#endif

}