// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessageEntityPre : ITLMessageEntityBase, TLMessageEntityPre 
	{
		public String Language { get; set; }

		public ITLMessageEntityPre() { }
		public ITLMessageEntityPre(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessageEntityPre; } }

		public override void Read(TLBinaryReader from)
		{
			Offset = from.ReadInt32();
			Length = from.ReadInt32();
			Language = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x73924BE0);
			to.Write(Offset);
			to.Write(Length);
			to.Write(Language);
		}
	}

#if !PORTABLE
	[Guid(0xe8a61fc9, 0xc157, 0xd711, 0x6e, 0xec, 0x85, 0x83, 0x43, 0x42, 0xe8, 0xce)]
	public partial interface TLMessageEntityPre : TLMessageEntityBase
	{
		Int32 Offset { get; set; }
		Int32 Length { get; set; }
		String Language { get; set; }
	}
#endif

}