// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessageActionChatDeleteUser : ITLMessageActionBase, TLMessageActionChatDeleteUser 
	{
		public Int32 UserId { get; set; }

		public ITLMessageActionChatDeleteUser() { }
		public ITLMessageActionChatDeleteUser(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessageActionChatDeleteUser; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB2AE9B0C);
			to.Write(UserId);
		}
	}

#if !PORTABLE
	[Guid(0xb7ad6125, 0xe49b, 0x6bc2, 0x5b, 0x0d, 0x45, 0x94, 0xee, 0x69, 0x89, 0x21)]
	public partial interface TLMessageActionChatDeleteUser : TLMessageActionBase
	{
		Int32 UserId { get; set; }
	}
#endif

}