// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessageEntityTextUrl : ITLMessageEntityBase, TLMessageEntityTextUrl 
	{
		public String Url { get; set; }

		public ITLMessageEntityTextUrl() { }
		public ITLMessageEntityTextUrl(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessageEntityTextUrl; } }

		public override void Read(TLBinaryReader from)
		{
			Offset = from.ReadInt32();
			Length = from.ReadInt32();
			Url = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x76A6D327);
			to.Write(Offset);
			to.Write(Length);
			to.Write(Url);
		}
	}

#if !PORTABLE
	[Guid(0xe8a61fc9, 0xc157, 0xd711, 0x6e, 0xec, 0x85, 0x83, 0x43, 0x42, 0xe8, 0xce)]
	public partial interface TLMessageEntityTextUrl : TLMessageEntityBase
	{
		Int32 Offset { get; set; }
		Int32 Length { get; set; }
		String Url { get; set; }
	}
#endif

}