// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesAllStickers : ITLMessagesAllStickersBase, TLMessagesAllStickers 
	{
		public Int32 Hash { get; set; }
		public TLVector<TLStickerSet> Sets { get; set; }

		public ITLMessagesAllStickers() { }
		public ITLMessagesAllStickers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesAllStickers; } }

		public override void Read(TLBinaryReader from)
		{
			Hash = from.ReadInt32();
			Sets = TLFactory.Read<TLVector<TLStickerSet>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEDFD405F);
			to.Write(Hash);
			to.WriteObject(Sets);
		}
	}

#if !PORTABLE
	[Guid(0x4cb693f4, 0x4cf4, 0x94dc, 0xc0, 0xcc, 0xa7, 0x4d, 0xdb, 0x48, 0x74, 0xd8)]
	public partial interface TLMessagesAllStickers : TLMessagesAllStickersBase
	{
		Int32 Hash { get; set; }
		TLVector<TLStickerSet> Sets { get; set; }
	}
#endif

}