// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesHighScores : ITLObject, TLMessagesHighScores 
	{
		public TLVector<TLHighScore> Scores { get; set; }
		public TLVector<TLUserBase> Users { get; set; }

		public ITLMessagesHighScores() { }
		public ITLMessagesHighScores(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesHighScores; } }

		public override void Read(TLBinaryReader from)
		{
			Scores = TLFactory.Read<TLVector<TLHighScore>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9A3BFD99);
			to.WriteObject(Scores);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0xf99197e1, 0xa9b4, 0x1b01, 0x96, 0xdf, 0x86, 0x3d, 0x3b, 0x0f, 0x00, 0x6d)]
	public partial interface TLMessagesHighScores : TLObject
	{
		TLVector<TLHighScore> Scores { get; set; }
		TLVector<TLUserBase> Users { get; set; }
	}
#endif

}