// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLMessagesChatsBase : TLObject, ITLMessagesChatsBase
	{
		public TLVector<TLChatBase> Chats { get; set; }
	}

	[Guid(0x4e5ee45d, 0x229b, 0x942f, 0x5e, 0x54, 0xa7, 0xaa, 0x85, 0x07, 0x70, 0xf8)]
	public partial interface ITLMessagesChatsBase : TLObject
	{
		TLVector<TLChatBase> Chats { get; set; }
	}
}