// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLMessageBase : TLObject, ITLMessageBase
	{
		public Int32 Id { get; set; }
		public Int32? FromId { get; set; }
		public TLPeerBase ToId { get; set; }
		public Int32? ReplyToMsgId { get; set; }
		public Int32 Date { get; set; }
	}

	[Guid(0x0231e778, 0x8f7d, 0x0ed5, 0xd6, 0x42, 0x34, 0x0b, 0x7c, 0x9a, 0x63, 0xb3)]
	public partial interface ITLMessageBase : TLObject
	{
		Int32 Id { get; set; }
		Int32? FromId { get; set; }
		TLPeerBase ToId { get; set; }
		Int32? ReplyToMsgId { get; set; }
		Int32 Date { get; set; }
	}
}