// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesAffectedHistory : ITLObject, TLMessagesAffectedHistory, ITLMultiPts 
	{
		public Int32 Pts { get; set; }
		public Int32 PtsCount { get; set; }
		public Int32 Offset { get; set; }

		public ITLMessagesAffectedHistory() { }
		public ITLMessagesAffectedHistory(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesAffectedHistory; } }

		public override void Read(TLBinaryReader from)
		{
			Pts = from.ReadInt32();
			PtsCount = from.ReadInt32();
			Offset = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB45C69D1);
			to.Write(Pts);
			to.Write(PtsCount);
			to.Write(Offset);
		}
	}

#if !PORTABLE
	[Guid(0x83405791, 0x3a6b, 0xb968, 0xf4, 0x51, 0x7e, 0x15, 0x6a, 0xef, 0x5e, 0xd2)]
	public partial interface TLMessagesAffectedHistory : TLObject
	{
		Int32 Pts { get; set; }
		Int32 PtsCount { get; set; }
		Int32 Offset { get; set; }
	}
#endif

}