// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLMessagesStickersBase : TLObject, ITLMessagesStickersBase
	{
	}

	[Guid(0x354c7e13, 0x1958, 0x0c49, 0x93, 0xac, 0x07, 0x48, 0x21, 0xb1, 0x05, 0x7f)]
	public partial interface ITLMessagesStickersBase : TLObject
	{
	}
}