// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesStickersNotModified : ITLMessagesStickersBase, TLMessagesStickersNotModified 
	{
		public ITLMessagesStickersNotModified() { }
		public ITLMessagesStickersNotModified(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesStickersNotModified; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF1749A22);
		}
	}

#if !PORTABLE
	[Guid(0x354c7e13, 0x1958, 0x0c49, 0x93, 0xac, 0x07, 0x48, 0x21, 0xb1, 0x05, 0x7f)]
	public partial interface TLMessagesStickersNotModified : TLMessagesStickersBase
	{
	}
#endif

}