// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesMessageEditData : ITLObject, TLMessagesMessageEditData 
	{
		public bool IsCaption { get { return Flags.HasFlag(TLMessagesMessageEditDataFlag.Caption); } set { Flags = value ? (Flags | TLMessagesMessageEditDataFlag.Caption) : (Flags & ~TLMessagesMessageEditDataFlag.Caption); } }

		public TLMessagesMessageEditDataFlag Flags { get; set; }

		public ITLMessagesMessageEditData() { }
		public ITLMessagesMessageEditData(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesMessageEditData; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLMessagesMessageEditDataFlag)from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x26B5DDE6);
			to.Write((Int32)Flags);
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLMessagesMessageEditDataFlag : Int32
	{
		Caption = (1 << 0),
	}
#endif

#if !PORTABLE
	[Guid(0x3a716c06, 0x909a, 0x8d5f, 0x27, 0x1b, 0xe1, 0xed, 0x60, 0x7f, 0x8f, 0xc1)]
	public partial interface TLMessagesMessageEditData : TLObject
	{
		bool IsCaption { get; set; }

		TLMessagesMessageEditDataFlag Flags { get; set; }
	}
#endif

}