// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLMessageCommonBase : TLMessageBase, ITLMessageCommonBase
	{
		public abstract bool IsOut { get; set; }
		public abstract bool IsMentioned { get; set; }
		public abstract bool IsMediaUnread { get; set; }
		public abstract bool IsSilent { get; set; }
		public abstract bool IsPost { get; set; }
	}

	[Guid(0xfbf501df, 0x2941, 0xc23a, 0x4c, 0x21, 0x44, 0x09, 0xfe, 0x3e, 0x26, 0x48)]
	public partial interface ITLMessageCommonBase : TLMessageBase
	{
		abstract bool IsOut { get; set; }
		abstract bool IsMentioned { get; set; }
		abstract bool IsMediaUnread { get; set; }
		abstract bool IsSilent { get; set; }
		abstract bool IsPost { get; set; }
	}
}