// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesMessagesSlice : ITLMessagesMessagesBase, TLMessagesMessagesSlice 
	{
		public Int32 Count { get; set; }

		public ITLMessagesMessagesSlice() { }
		public ITLMessagesMessagesSlice(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesMessagesSlice; } }

		public override void Read(TLBinaryReader from)
		{
			Count = from.ReadInt32();
			Messages = TLFactory.Read<TLVector<TLMessageBase>>(from);
			Chats = TLFactory.Read<TLVector<TLChatBase>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB446AE3);
			to.Write(Count);
			to.WriteObject(Messages);
			to.WriteObject(Chats);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0x136920a5, 0xc016, 0xafe2, 0x62, 0x0d, 0xf2, 0x74, 0x96, 0xa0, 0x45, 0x01)]
	public partial interface TLMessagesMessagesSlice : TLMessagesMessagesBase
	{
		Int32 Count { get; set; }
		TLVector<TLMessageBase> Messages { get; set; }
		TLVector<TLChatBase> Chats { get; set; }
		TLVector<TLUserBase> Users { get; set; }
	}
#endif

}