// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesSavedGifs : ITLMessagesSavedGifsBase, TLMessagesSavedGifs 
	{
		public Int32 Hash { get; set; }
		public TLVector<TLDocumentBase> Gifs { get; set; }

		public ITLMessagesSavedGifs() { }
		public ITLMessagesSavedGifs(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesSavedGifs; } }

		public override void Read(TLBinaryReader from)
		{
			Hash = from.ReadInt32();
			Gifs = TLFactory.Read<TLVector<TLDocumentBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x2E0709A5);
			to.Write(Hash);
			to.WriteObject(Gifs);
		}
	}

#if !PORTABLE
	[Guid(0x9513f32f, 0xeb51, 0xb5b4, 0x61, 0xec, 0x80, 0x66, 0xfd, 0xa0, 0xdc, 0xc3)]
	public partial interface TLMessagesSavedGifs : TLMessagesSavedGifsBase
	{
		Int32 Hash { get; set; }
		TLVector<TLDocumentBase> Gifs { get; set; }
	}
#endif

}