// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesStickerSetInstallResultSuccess : ITLMessagesStickerSetInstallResultBase, TLMessagesStickerSetInstallResultSuccess 
	{
		public ITLMessagesStickerSetInstallResultSuccess() { }
		public ITLMessagesStickerSetInstallResultSuccess(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesStickerSetInstallResultSuccess; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x38641628);
		}
	}

#if !PORTABLE
	[Guid(0xa22fcd0b, 0x1ce4, 0xa45d, 0xed, 0x7c, 0xfe, 0x72, 0xf0, 0x4b, 0x2b, 0xce)]
	public partial interface TLMessagesStickerSetInstallResultSuccess : TLMessagesStickerSetInstallResultBase
	{
	}
#endif

}