// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
	#else
	public
#endif
	abstract partial class ITLMsgDetailedInfoBase : ITLObject, TLMsgDetailedInfoBase
	{
		public Int64 AnswerMsgId { get; set; }
		public Int32 Bytes { get; set; }
		public Int32 Status { get; set; }
	}

#if !PORTABLE
	[Guid(0x8b76ed70, 0x7744, 0xda87, 0x1e, 0xd0, 0x87, 0x5d, 0x82, 0xf7, 0x75, 0x37)]
	public partial interface TLMsgDetailedInfoBase : TLObject
	{
		Int64 AnswerMsgId { get; set; }
		Int32 Bytes { get; set; }
		Int32 Status { get; set; }
	}
#endif

}