// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMsgNewDetailedInfo : ITLMsgDetailedInfoBase, TLMsgNewDetailedInfo 
	{
		public ITLMsgNewDetailedInfo() { }
		public ITLMsgNewDetailedInfo(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MsgNewDetailedInfo; } }

		public override void Read(TLBinaryReader from)
		{
			AnswerMsgId = from.ReadInt64();
			Bytes = from.ReadInt32();
			Status = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x809DB6DF);
			to.Write(AnswerMsgId);
			to.Write(Bytes);
			to.Write(Status);
		}
	}

#if !PORTABLE
	[Guid(0x8b76ed70, 0x7744, 0xda87, 0x1e, 0xd0, 0x87, 0x5d, 0x82, 0xf7, 0x75, 0x37)]
	public partial interface TLMsgNewDetailedInfo : TLMsgDetailedInfoBase
	{
		Int64 AnswerMsgId { get; set; }
		Int32 Bytes { get; set; }
		Int32 Status { get; set; }
	}
#endif

}