// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLNearestDC : ITLObject, TLNearestDC 
	{
		public String Country { get; set; }
		public Int32 ThisDC { get; set; }
		public Int32 NearestDC { get; set; }

		public ITLNearestDC() { }
		public ITLNearestDC(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.NearestDC; } }

		public override void Read(TLBinaryReader from)
		{
			Country = from.ReadString();
			ThisDC = from.ReadInt32();
			NearestDC = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x8E1A1775);
			to.Write(Country);
			to.Write(ThisDC);
			to.Write(NearestDC);
		}
	}

#if !PORTABLE
	[Guid(0x3ecd4da6, 0x38b5, 0xaa03, 0x8a, 0x7d, 0x45, 0xc6, 0xb3, 0xd4, 0x6f, 0xd7)]
	public partial interface TLNearestDC : TLObject
	{
		String Country { get; set; }
		Int32 ThisDC { get; set; }
		Int32 NearestDC { get; set; }
	}
#endif

}