// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLNotifyChats : ITLNotifyPeerBase, TLNotifyChats 
	{
		public ITLNotifyChats() { }
		public ITLNotifyChats(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.NotifyChats; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC007CEC3);
		}
	}

#if !PORTABLE
	[Guid(0x82bcf8ac, 0xa7ee, 0xe104, 0xe4, 0xda, 0x58, 0x25, 0x14, 0xed, 0xa3, 0xaf)]
	public partial interface TLNotifyChats : TLNotifyPeerBase
	{
	}
#endif

}