// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLPageBase : TLObject, ITLPageBase
	{
		public TLVector<TLPageBlockBase> Blocks { get; set; }
		public TLVector<TLPhotoBase> Photos { get; set; }
		public TLVector<TLDocumentBase> Videos { get; set; }
	}

	[Guid(0x770c8671, 0x74c6, 0x7953, 0xb0, 0xd4, 0x43, 0x04, 0xd6, 0x6b, 0x6a, 0x13)]
	public partial interface ITLPageBase : TLObject
	{
		TLVector<TLPageBlockBase> Blocks { get; set; }
		TLVector<TLPhotoBase> Photos { get; set; }
		TLVector<TLDocumentBase> Videos { get; set; }
	}
}