// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPaymentCharge : ITLObject, TLPaymentCharge 
	{
		public String Id { get; set; }
		public String ProviderChargeId { get; set; }

		public ITLPaymentCharge() { }
		public ITLPaymentCharge(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PaymentCharge; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadString();
			ProviderChargeId = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEA02C27E);
			to.Write(Id);
			to.Write(ProviderChargeId);
		}
	}

#if !PORTABLE
	[Guid(0xa24eb405, 0x86bf, 0xd407, 0x85, 0xc7, 0xac, 0xf8, 0x81, 0xd1, 0x32, 0xc7)]
	public partial interface TLPaymentCharge : TLObject
	{
		String Id { get; set; }
		String ProviderChargeId { get; set; }
	}
#endif

}