// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPageBlockPullquote : ITLPageBlockBase, TLPageBlockPullquote 
	{
		public TLRichTextBase Text { get; set; }
		public TLRichTextBase Caption { get; set; }

		public ITLPageBlockPullquote() { }
		public ITLPageBlockPullquote(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PageBlockPullquote; } }

		public override void Read(TLBinaryReader from)
		{
			Text = TLFactory.Read<TLRichTextBase>(from);
			Caption = TLFactory.Read<TLRichTextBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4F4456D3);
			to.WriteObject(Text);
			to.WriteObject(Caption);
		}
	}

#if !PORTABLE
	[Guid(0x784d446a, 0x4e73, 0x3e67, 0xb1, 0x20, 0xe8, 0xd2, 0xc6, 0xec, 0x8d, 0x4d)]
	public partial interface TLPageBlockPullquote : TLPageBlockBase
	{
		TLRichTextBase Text { get; set; }
		TLRichTextBase Caption { get; set; }
	}
#endif

}