// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPaymentsSavedInfo : ITLObject, TLPaymentsSavedInfo 
	{
		public bool IsHasSavedCredentials { get { return Flags.HasFlag(TLPaymentsSavedInfoFlag.HasSavedCredentials); } set { Flags = value ? (Flags | TLPaymentsSavedInfoFlag.HasSavedCredentials) : (Flags & ~TLPaymentsSavedInfoFlag.HasSavedCredentials); } }
		public bool HasSavedInfo { get { return Flags.HasFlag(TLPaymentsSavedInfoFlag.SavedInfo); } set { Flags = value ? (Flags | TLPaymentsSavedInfoFlag.SavedInfo) : (Flags & ~TLPaymentsSavedInfoFlag.SavedInfo); } }

		public TLPaymentsSavedInfoFlag Flags { get; set; }
		public TLPaymentRequestedInfo SavedInfo { get; set; }

		public ITLPaymentsSavedInfo() { }
		public ITLPaymentsSavedInfo(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PaymentsSavedInfo; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLPaymentsSavedInfoFlag)from.ReadInt32();
			if (HasSavedInfo) SavedInfo = TLFactory.Read<TLPaymentRequestedInfo>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			UpdateFlags();

			to.Write(0xFB8FE43C);
			to.Write((Int32)Flags);
			if (HasSavedInfo) to.WriteObject(SavedInfo);
		}

		private void UpdateFlags()
		{
			HasSavedInfo = SavedInfo != null;
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLPaymentsSavedInfoFlag : Int32
	{
		HasSavedCredentials = (1 << 1),
		SavedInfo = (1 << 0),
	}
#endif

#if !PORTABLE
	[Guid(0x8bd24cba, 0x079e, 0x216c, 0x6a, 0xe7, 0xb8, 0xf2, 0xb9, 0xc0, 0x4a, 0xbc)]
	public partial interface TLPaymentsSavedInfo : TLObject
	{
		bool IsHasSavedCredentials { get; set; }
		bool HasSavedInfo { get; set; }

		TLPaymentsSavedInfoFlag Flags { get; set; }
		TLPaymentRequestedInfo SavedInfo { get; set; }
	}
#endif

}