// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLPaymentSavedCredentialsBase : TLObject, ITLPaymentSavedCredentialsBase
	{
	}

	[Guid(0xdb154750, 0x74f7, 0x4256, 0x26, 0x74, 0x11, 0x14, 0x31, 0xc5, 0xd1, 0x5d)]
	public partial interface ITLPaymentSavedCredentialsBase : TLObject
	{
	}
}