// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPeerNotifySettingsEmpty : ITLPeerNotifySettingsBase, TLPeerNotifySettingsEmpty 
	{
		public ITLPeerNotifySettingsEmpty() { }
		public ITLPeerNotifySettingsEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PeerNotifySettingsEmpty; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x70A68512);
		}
	}

#if !PORTABLE
	[Guid(0x79d0067e, 0xcc94, 0x732c, 0xe1, 0xa3, 0x1e, 0x85, 0x8f, 0x5a, 0xc5, 0x11)]
	public partial interface TLPeerNotifySettingsEmpty : TLPeerNotifySettingsBase
	{
	}
#endif

}