// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLPhotoBase : TLObject, ITLPhotoBase
	{
		public Int64 Id { get; set; }
	}

	[Guid(0xc8c1e05a, 0x26a5, 0xc70b, 0xb6, 0x64, 0x8f, 0x6f, 0xbd, 0x11, 0x5c, 0x35)]
	public partial interface ITLPhotoBase : TLObject
	{
		Int64 Id { get; set; }
	}
}