// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLPhotoSizeBase : TLObject, ITLPhotoSizeBase
	{
		public String Type { get; set; }
	}

	[Guid(0x365c79bd, 0x40a8, 0xa833, 0xe8, 0x83, 0x5f, 0x61, 0xf0, 0xcc, 0xe4, 0x5f)]
	public partial interface ITLPhotoSizeBase : TLObject
	{
		String Type { get; set; }
	}
}