// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPhoneCallEmpty : ITLPhoneCallBase, TLPhoneCallEmpty 
	{
		public ITLPhoneCallEmpty() { }
		public ITLPhoneCallEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhoneCallEmpty; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x5366C915);
			to.Write(Id);
		}
	}

#if !PORTABLE
	[Guid(0x8aab306d, 0x4218, 0x45d3, 0x35, 0x19, 0x67, 0x9a, 0xea, 0x50, 0xa9, 0x1a)]
	public partial interface TLPhoneCallEmpty : TLPhoneCallBase
	{
		Int64 Id { get; set; }
	}
#endif

}