// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPhotoSizeEmpty : ITLPhotoSizeBase, TLPhotoSizeEmpty 
	{
		public ITLPhotoSizeEmpty() { }
		public ITLPhotoSizeEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhotoSizeEmpty; } }

		public override void Read(TLBinaryReader from)
		{
			Type = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE17E23C);
			to.Write(Type);
		}
	}

#if !PORTABLE
	[Guid(0x365c79bd, 0x40a8, 0xa833, 0xe8, 0x83, 0x5f, 0x61, 0xf0, 0xcc, 0xe4, 0x5f)]
	public partial interface TLPhotoSizeEmpty : TLPhotoSizeBase
	{
		String Type { get; set; }
	}
#endif

}