// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPhoneCallDiscardReasonBusy : ITLPhoneCallDiscardReasonBase, TLPhoneCallDiscardReasonBusy 
	{
		public ITLPhoneCallDiscardReasonBusy() { }
		public ITLPhoneCallDiscardReasonBusy(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhoneCallDiscardReasonBusy; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xFAF7E8C9);
		}
	}

#if !PORTABLE
	[Guid(0x42ac5e78, 0x7ef5, 0x3963, 0xda, 0x6a, 0x69, 0xc2, 0x6a, 0xbe, 0xf4, 0x63)]
	public partial interface TLPhoneCallDiscardReasonBusy : TLPhoneCallDiscardReasonBase
	{
	}
#endif

}