// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPrivacyValueDisallowContacts : ITLPrivacyRuleBase, TLPrivacyValueDisallowContacts 
	{
		public ITLPrivacyValueDisallowContacts() { }
		public ITLPrivacyValueDisallowContacts(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PrivacyValueDisallowContacts; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF888FA1A);
		}
	}

#if !PORTABLE
	[Guid(0xbaac970d, 0x55ce, 0x0b16, 0x98, 0x87, 0xd8, 0xb1, 0x40, 0x04, 0xed, 0x28)]
	public partial interface TLPrivacyValueDisallowContacts : TLPrivacyRuleBase
	{
	}
#endif

}