// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPrivacyValueDisallowUsers : ITLPrivacyRuleBase, TLPrivacyValueDisallowUsers 
	{
		public TLVector<Int32> Users { get; set; }

		public ITLPrivacyValueDisallowUsers() { }
		public ITLPrivacyValueDisallowUsers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PrivacyValueDisallowUsers; } }

		public override void Read(TLBinaryReader from)
		{
			Users = TLFactory.Read<TLVector<Int32>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC7F49B7);
			to.WriteObject(Users);
		}
	}

#if !PORTABLE
	[Guid(0xbaac970d, 0x55ce, 0x0b16, 0x98, 0x87, 0xd8, 0xb1, 0x40, 0x04, 0xed, 0x28)]
	public partial interface TLPrivacyValueDisallowUsers : TLPrivacyRuleBase
	{
		TLVector<Int32> Users { get; set; }
	}
#endif

}