// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
	public abstract partial class TLReportReasonBase : TLObject, ITLReportReasonBase
	{
	}

	[Guid(0x69c7d797, 0x483d, 0x9458, 0xe4, 0x04, 0x43, 0x5c, 0x8c, 0x9b, 0xad, 0x2a)]
	public partial interface ITLReportReasonBase : TLObject
	{
	}
}