// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
	#else
	public
#endif
	abstract partial class ITLReplyMarkupBase : ITLObject, TLReplyMarkupBase
	{
	}

#if !PORTABLE
	[Guid(0xbf780e09, 0x4654, 0x7369, 0xe6, 0x54, 0x8b, 0xb2, 0x75, 0x41, 0x0d, 0xf2)]
	public partial interface TLReplyMarkupBase : TLObject
	{
	}
#endif

}