// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLReceivedNotifyMessage : ITLObject, TLReceivedNotifyMessage 
	{
		public Int32 Id { get; set; }
		public Int32 Flags { get; set; }

		public ITLReceivedNotifyMessage() { }
		public ITLReceivedNotifyMessage(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ReceivedNotifyMessage; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt32();
			Flags = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xA384B779);
			to.Write(Id);
			to.Write(Flags);
		}
	}

#if !PORTABLE
	[Guid(0x2b8b447c, 0x221a, 0xb15f, 0x05, 0x56, 0x90, 0xdb, 0x2a, 0x2d, 0xb1, 0x7d)]
	public partial interface TLReceivedNotifyMessage : TLObject
	{
		Int32 Id { get; set; }
		Int32 Flags { get; set; }
	}
#endif

}