// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLRPCAnswerDroppedRunning : ITLRPCDropAnswerBase, TLRPCAnswerDroppedRunning 
	{
		public ITLRPCAnswerDroppedRunning() { }
		public ITLRPCAnswerDroppedRunning(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.RPCAnswerDroppedRunning; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xCD78E586);
		}
	}

#if !PORTABLE
	[Guid(0x4ddf16e9, 0xddbd, 0xa4d8, 0x99, 0x92, 0xd6, 0xe4, 0x37, 0x91, 0x2b, 0xc4)]
	public partial interface TLRPCAnswerDroppedRunning : TLRPCDropAnswerBase
	{
	}
#endif

}