// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLSendMessageTypingAction : ITLSendMessageActionBase, TLSendMessageTypingAction 
	{
		public ITLSendMessageTypingAction() { }
		public ITLSendMessageTypingAction(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.SendMessageTypingAction; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x16BF744E);
		}
	}

#if !PORTABLE
	[Guid(0x991dd7ea, 0x97f9, 0x9c29, 0x8a, 0x70, 0x66, 0xbd, 0x97, 0x76, 0xf3, 0xb7)]
	public partial interface TLSendMessageTypingAction : TLSendMessageActionBase
	{
	}
#endif

}