// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLStorageFileMp4 : ITLStorageFileTypeBase, TLStorageFileMp4 
	{
		public ITLStorageFileMp4() { }
		public ITLStorageFileMp4(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.StorageFileMp4; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB3CEA0E4);
		}
	}

#if !PORTABLE
	[Guid(0x18068029, 0xeb39, 0x8ea6, 0xf0, 0xfc, 0x4c, 0xee, 0x26, 0x8c, 0x5c, 0xef)]
	public partial interface TLStorageFileMp4 : TLStorageFileTypeBase
	{
	}
#endif

}