// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLStickerSetMultiCovered : ITLStickerSetCoveredBase, TLStickerSetMultiCovered 
	{
		public TLVector<TLDocumentBase> Covers { get; set; }

		public ITLStickerSetMultiCovered() { }
		public ITLStickerSetMultiCovered(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.StickerSetMultiCovered; } }

		public override void Read(TLBinaryReader from)
		{
			Set = TLFactory.Read<TLStickerSet>(from);
			Covers = TLFactory.Read<TLVector<TLDocumentBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3407E51B);
			to.WriteObject(Set);
			to.WriteObject(Covers);
		}
	}

#if !PORTABLE
	[Guid(0x096f5c92, 0x4654, 0x7fd9, 0x3b, 0x9c, 0xd8, 0x80, 0xf1, 0xc8, 0x78, 0xd7)]
	public partial interface TLStickerSetMultiCovered : TLStickerSetCoveredBase
	{
		TLStickerSet Set { get; set; }
		TLVector<TLDocumentBase> Covers { get; set; }
	}
#endif

}