// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLStickerSetCovered : ITLStickerSetCoveredBase, TLStickerSetCovered 
	{
		public TLDocumentBase Cover { get; set; }

		public ITLStickerSetCovered() { }
		public ITLStickerSetCovered(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.StickerSetCovered; } }

		public override void Read(TLBinaryReader from)
		{
			Set = TLFactory.Read<TLStickerSet>(from);
			Cover = TLFactory.Read<TLDocumentBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x6410A5D2);
			to.WriteObject(Set);
			to.WriteObject(Cover);
		}
	}

#if !PORTABLE
	[Guid(0x096f5c92, 0x4654, 0x7fd9, 0x3b, 0x9c, 0xd8, 0x80, 0xf1, 0xc8, 0x78, 0xd7)]
	public partial interface TLStickerSetCovered : TLStickerSetCoveredBase
	{
		TLStickerSet Set { get; set; }
		TLDocumentBase Cover { get; set; }
	}
#endif

}