// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLTextUnderline : ITLRichTextBase, TLTextUnderline 
	{
		public TLRichTextBase Text { get; set; }

		public ITLTextUnderline() { }
		public ITLTextUnderline(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.TextUnderline; } }

		public override void Read(TLBinaryReader from)
		{
			Text = TLFactory.Read<TLRichTextBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC12622C4);
			to.WriteObject(Text);
		}
	}

#if !PORTABLE
	[Guid(0xf40e2a31, 0x55d7, 0xc2fa, 0xcb, 0xa6, 0x68, 0xad, 0xba, 0xde, 0x81, 0xc0)]
	public partial interface TLTextUnderline : TLRichTextBase
	{
		TLRichTextBase Text { get; set; }
	}
#endif

}