// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLTextUrl : ITLRichTextBase, TLTextUrl 
	{
		public TLRichTextBase Text { get; set; }
		public String Url { get; set; }
		public Int64 WebPageId { get; set; }

		public ITLTextUrl() { }
		public ITLTextUrl(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.TextUrl; } }

		public override void Read(TLBinaryReader from)
		{
			Text = TLFactory.Read<TLRichTextBase>(from);
			Url = from.ReadString();
			WebPageId = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3C2884C1);
			to.WriteObject(Text);
			to.Write(Url);
			to.Write(WebPageId);
		}
	}

#if !PORTABLE
	[Guid(0xf40e2a31, 0x55d7, 0xc2fa, 0xcb, 0xa6, 0x68, 0xad, 0xba, 0xde, 0x81, 0xc0)]
	public partial interface TLTextUrl : TLRichTextBase
	{
		TLRichTextBase Text { get; set; }
		String Url { get; set; }
		Int64 WebPageId { get; set; }
	}
#endif

}