// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLTextConcat : ITLRichTextBase, TLTextConcat 
	{
		public TLVector<TLRichTextBase> Texts { get; set; }

		public ITLTextConcat() { }
		public ITLTextConcat(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.TextConcat; } }

		public override void Read(TLBinaryReader from)
		{
			Texts = TLFactory.Read<TLVector<TLRichTextBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x7E6260D7);
			to.WriteObject(Texts);
		}
	}

#if !PORTABLE
	[Guid(0xf40e2a31, 0x55d7, 0xc2fa, 0xcb, 0xa6, 0x68, 0xad, 0xba, 0xde, 0x81, 0xc0)]
	public partial interface TLTextConcat : TLRichTextBase
	{
		TLVector<TLRichTextBase> Texts { get; set; }
	}
#endif

}