// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLTextBold : ITLRichTextBase, TLTextBold 
	{
		public TLRichTextBase Text { get; set; }

		public ITLTextBold() { }
		public ITLTextBold(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.TextBold; } }

		public override void Read(TLBinaryReader from)
		{
			Text = TLFactory.Read<TLRichTextBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x6724ABC4);
			to.WriteObject(Text);
		}
	}

#if !PORTABLE
	[Guid(0xf40e2a31, 0x55d7, 0xc2fa, 0xcb, 0xa6, 0x68, 0xad, 0xba, 0xde, 0x81, 0xc0)]
	public partial interface TLTextBold : TLRichTextBase
	{
		TLRichTextBase Text { get; set; }
	}
#endif

}