// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLTopPeerCategoryBotsPM : ITLTopPeerCategoryBase, TLTopPeerCategoryBotsPM 
	{
		public ITLTopPeerCategoryBotsPM() { }
		public ITLTopPeerCategoryBotsPM(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.TopPeerCategoryBotsPM; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xAB661B5B);
		}
	}

#if !PORTABLE
	[Guid(0x670a8ef2, 0x944e, 0x7a85, 0xec, 0x99, 0xdb, 0x22, 0x25, 0x2e, 0x1b, 0x75)]
	public partial interface TLTopPeerCategoryBotsPM : TLTopPeerCategoryBase
	{
	}
#endif

}