// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLTopPeerCategoryCorrespondents : ITLTopPeerCategoryBase, TLTopPeerCategoryCorrespondents 
	{
		public ITLTopPeerCategoryCorrespondents() { }
		public ITLTopPeerCategoryCorrespondents(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.TopPeerCategoryCorrespondents; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x637B7ED);
		}
	}

#if !PORTABLE
	[Guid(0x670a8ef2, 0x944e, 0x7a85, 0xec, 0x99, 0xdb, 0x22, 0x25, 0x2e, 0x1b, 0x75)]
	public partial interface TLTopPeerCategoryCorrespondents : TLTopPeerCategoryBase
	{
	}
#endif

}