// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLTopPeer : ITLObject, TLTopPeer 
	{
		public TLPeerBase Peer { get; set; }
		public Double Rating { get; set; }

		public ITLTopPeer() { }
		public ITLTopPeer(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.TopPeer; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLPeerBase>(from);
			Rating = from.ReadDouble();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEDCDC05B);
			to.WriteObject(Peer);
			to.Write(Rating);
		}
	}

#if !PORTABLE
	[Guid(0x246c6e6a, 0xb506, 0xe227, 0x42, 0xee, 0x19, 0x08, 0xe0, 0xf9, 0xf5, 0x06)]
	public partial interface TLTopPeer : TLObject
	{
		TLPeerBase Peer { get; set; }
		Double Rating { get; set; }
	}
#endif

}