// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateEncryptedMessagesRead : ITLUpdateBase, TLUpdateEncryptedMessagesRead 
	{
		public Int32 ChatId { get; set; }
		public Int32 MaxDate { get; set; }
		public Int32 Date { get; set; }

		public ITLUpdateEncryptedMessagesRead() { }
		public ITLUpdateEncryptedMessagesRead(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateEncryptedMessagesRead; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
			MaxDate = from.ReadInt32();
			Date = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x38FE25B7);
			to.Write(ChatId);
			to.Write(MaxDate);
			to.Write(Date);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateEncryptedMessagesRead : TLUpdateBase
	{
		Int32 ChatId { get; set; }
		Int32 MaxDate { get; set; }
		Int32 Date { get; set; }
	}
#endif

}