// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdatePhoneCall : ITLUpdateBase, TLUpdatePhoneCall 
	{
		public TLPhoneCallBase PhoneCall { get; set; }

		public ITLUpdatePhoneCall() { }
		public ITLUpdatePhoneCall(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdatePhoneCall; } }

		public override void Read(TLBinaryReader from)
		{
			PhoneCall = TLFactory.Read<TLPhoneCallBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xAB0F6B1E);
			to.WriteObject(PhoneCall);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdatePhoneCall : TLUpdateBase
	{
		TLPhoneCallBase PhoneCall { get; set; }
	}
#endif

}