// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateChatParticipants : ITLUpdateBase, TLUpdateChatParticipants 
	{
		public TLChatParticipantsBase Participants { get; set; }

		public ITLUpdateChatParticipants() { }
		public ITLUpdateChatParticipants(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateChatParticipants; } }

		public override void Read(TLBinaryReader from)
		{
			Participants = TLFactory.Read<TLChatParticipantsBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x7761198);
			to.WriteObject(Participants);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateChatParticipants : TLUpdateBase
	{
		TLChatParticipantsBase Participants { get; set; }
	}
#endif

}