// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateContactRegistered : ITLUpdateBase, TLUpdateContactRegistered 
	{
		public Int32 UserId { get; set; }
		public Int32 Date { get; set; }

		public ITLUpdateContactRegistered() { }
		public ITLUpdateContactRegistered(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateContactRegistered; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
			Date = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x2575BBB9);
			to.Write(UserId);
			to.Write(Date);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateContactRegistered : TLUpdateBase
	{
		Int32 UserId { get; set; }
		Int32 Date { get; set; }
	}
#endif

}