// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateBotWebhookJSONQuery : ITLUpdateBase, TLUpdateBotWebhookJSONQuery 
	{
		public Int64 QueryId { get; set; }
		public TLDataJSON Data { get; set; }
		public Int32 Timeout { get; set; }

		public ITLUpdateBotWebhookJSONQuery() { }
		public ITLUpdateBotWebhookJSONQuery(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateBotWebhookJSONQuery; } }

		public override void Read(TLBinaryReader from)
		{
			QueryId = from.ReadInt64();
			Data = TLFactory.Read<TLDataJSON>(from);
			Timeout = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9B9240A6);
			to.Write(QueryId);
			to.WriteObject(Data);
			to.Write(Timeout);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateBotWebhookJSONQuery : TLUpdateBase
	{
		Int64 QueryId { get; set; }
		TLDataJSON Data { get; set; }
		Int32 Timeout { get; set; }
	}
#endif

}