// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateEncryption : ITLUpdateBase, TLUpdateEncryption 
	{
		public TLEncryptedChatBase Chat { get; set; }
		public Int32 Date { get; set; }

		public ITLUpdateEncryption() { }
		public ITLUpdateEncryption(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateEncryption; } }

		public override void Read(TLBinaryReader from)
		{
			Chat = TLFactory.Read<TLEncryptedChatBase>(from);
			Date = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB4A2E88D);
			to.WriteObject(Chat);
			to.Write(Date);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateEncryption : TLUpdateBase
	{
		TLEncryptedChatBase Chat { get; set; }
		Int32 Date { get; set; }
	}
#endif

}