// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateUserPhoto : ITLUpdateBase, TLUpdateUserPhoto 
	{
		public Int32 UserId { get; set; }
		public Int32 Date { get; set; }
		public TLUserProfilePhotoBase Photo { get; set; }
		public Boolean Previous { get; set; }

		public ITLUpdateUserPhoto() { }
		public ITLUpdateUserPhoto(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateUserPhoto; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
			Date = from.ReadInt32();
			Photo = TLFactory.Read<TLUserProfilePhotoBase>(from);
			Previous = from.ReadBoolean();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x95313B0C);
			to.Write(UserId);
			to.Write(Date);
			to.WriteObject(Photo);
			to.Write(Previous);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateUserPhoto : TLUpdateBase
	{
		Int32 UserId { get; set; }
		Int32 Date { get; set; }
		TLUserProfilePhotoBase Photo { get; set; }
		Boolean Previous { get; set; }
	}
#endif

}