// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateDeleteChannelMessages : ITLUpdateBase, TLUpdateDeleteChannelMessages, ITLMultiPts 
	{
		public Int32 ChannelId { get; set; }
		public TLVector<Int32> Messages { get; set; }
		public Int32 Pts { get; set; }
		public Int32 PtsCount { get; set; }

		public ITLUpdateDeleteChannelMessages() { }
		public ITLUpdateDeleteChannelMessages(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateDeleteChannelMessages; } }

		public override void Read(TLBinaryReader from)
		{
			ChannelId = from.ReadInt32();
			Messages = TLFactory.Read<TLVector<Int32>>(from);
			Pts = from.ReadInt32();
			PtsCount = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC37521C9);
			to.Write(ChannelId);
			to.WriteObject(Messages);
			to.Write(Pts);
			to.Write(PtsCount);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateDeleteChannelMessages : TLUpdateBase
	{
		Int32 ChannelId { get; set; }
		TLVector<Int32> Messages { get; set; }
		Int32 Pts { get; set; }
		Int32 PtsCount { get; set; }
	}
#endif

}