// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateChannel : ITLUpdateBase, TLUpdateChannel 
	{
		public Int32 ChannelId { get; set; }

		public ITLUpdateChannel() { }
		public ITLUpdateChannel(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateChannel; } }

		public override void Read(TLBinaryReader from)
		{
			ChannelId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB6D45656);
			to.Write(ChannelId);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateChannel : TLUpdateBase
	{
		Int32 ChannelId { get; set; }
	}
#endif

}