// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateChannelWebPage : ITLUpdateBase, TLUpdateChannelWebPage, ITLMultiPts 
	{
		public Int32 ChannelId { get; set; }
		public TLWebPageBase WebPage { get; set; }
		public Int32 Pts { get; set; }
		public Int32 PtsCount { get; set; }

		public ITLUpdateChannelWebPage() { }
		public ITLUpdateChannelWebPage(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateChannelWebPage; } }

		public override void Read(TLBinaryReader from)
		{
			ChannelId = from.ReadInt32();
			WebPage = TLFactory.Read<TLWebPageBase>(from);
			Pts = from.ReadInt32();
			PtsCount = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x40771900);
			to.Write(ChannelId);
			to.WriteObject(WebPage);
			to.Write(Pts);
			to.Write(PtsCount);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateChannelWebPage : TLUpdateBase
	{
		Int32 ChannelId { get; set; }
		TLWebPageBase WebPage { get; set; }
		Int32 Pts { get; set; }
		Int32 PtsCount { get; set; }
	}
#endif

}