// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdatesDifferenceEmpty : ITLUpdatesDifferenceBase, TLUpdatesDifferenceEmpty 
	{
		public Int32 Date { get; set; }
		public Int32 Seq { get; set; }

		public ITLUpdatesDifferenceEmpty() { }
		public ITLUpdatesDifferenceEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdatesDifferenceEmpty; } }

		public override void Read(TLBinaryReader from)
		{
			Date = from.ReadInt32();
			Seq = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x5D75A138);
			to.Write(Date);
			to.Write(Seq);
		}
	}

#if !PORTABLE
	[Guid(0x7c8c2e4d, 0x8e8e, 0x99b6, 0x1d, 0x70, 0xe7, 0xfa, 0x4c, 0x7e, 0x35, 0xb8)]
	public partial interface TLUpdatesDifferenceEmpty : TLUpdatesDifferenceBase
	{
		Int32 Date { get; set; }
		Int32 Seq { get; set; }
	}
#endif

}