// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUploadFile : ITLObject, TLUploadFile 
	{
		public TLStorageFileTypeBase Type { get; set; }
		public Int32 Mtime { get; set; }
		public Byte[] Bytes { get; set; }

		public ITLUploadFile() { }
		public ITLUploadFile(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UploadFile; } }

		public override void Read(TLBinaryReader from)
		{
			Type = TLFactory.Read<TLStorageFileTypeBase>(from);
			Mtime = from.ReadInt32();
			Bytes = from.ReadByteArray();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x96A18D5);
			to.WriteObject(Type);
			to.Write(Mtime);
			to.WriteByteArray(Bytes);
		}
	}

#if !PORTABLE
	[Guid(0x56bc10c3, 0x01a5, 0xb973, 0xc7, 0x40, 0x2d, 0x14, 0xef, 0x35, 0x89, 0x1d)]
	public partial interface TLUploadFile : TLObject
	{
		TLStorageFileTypeBase Type { get; set; }
		Int32 Mtime { get; set; }
		Byte[] Bytes { get; set; }
	}
#endif

}