// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateEditChannelMessage : ITLUpdateBase, TLUpdateEditChannelMessage, ITLMultiPts 
	{
		public TLMessageBase Message { get; set; }
		public Int32 Pts { get; set; }
		public Int32 PtsCount { get; set; }

		public ITLUpdateEditChannelMessage() { }
		public ITLUpdateEditChannelMessage(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateEditChannelMessage; } }

		public override void Read(TLBinaryReader from)
		{
			Message = TLFactory.Read<TLMessageBase>(from);
			Pts = from.ReadInt32();
			PtsCount = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x1B3F4DF7);
			to.WriteObject(Message);
			to.Write(Pts);
			to.Write(PtsCount);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateEditChannelMessage : TLUpdateBase
	{
		TLMessageBase Message { get; set; }
		Int32 Pts { get; set; }
		Int32 PtsCount { get; set; }
	}
#endif

}