// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateChatAdmins : ITLUpdateBase, TLUpdateChatAdmins 
	{
		public Int32 ChatId { get; set; }
		public Boolean Enabled { get; set; }
		public Int32 Version { get; set; }

		public ITLUpdateChatAdmins() { }
		public ITLUpdateChatAdmins(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateChatAdmins; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
			Enabled = from.ReadBoolean();
			Version = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x6E947941);
			to.Write(ChatId);
			to.Write(Enabled);
			to.Write(Version);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateChatAdmins : TLUpdateBase
	{
		Int32 ChatId { get; set; }
		Boolean Enabled { get; set; }
		Int32 Version { get; set; }
	}
#endif

}