// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateBotInlineQuery : ITLUpdateBase, TLUpdateBotInlineQuery 
	{
		public bool HasGeo { get { return Flags.HasFlag(TLUpdateBotInlineQueryFlag.Geo); } set { Flags = value ? (Flags | TLUpdateBotInlineQueryFlag.Geo) : (Flags & ~TLUpdateBotInlineQueryFlag.Geo); } }

		public TLUpdateBotInlineQueryFlag Flags { get; set; }
		public Int64 QueryId { get; set; }
		public Int32 UserId { get; set; }
		public String Query { get; set; }
		public TLGeoPointBase Geo { get; set; }
		public String Offset { get; set; }

		public ITLUpdateBotInlineQuery() { }
		public ITLUpdateBotInlineQuery(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateBotInlineQuery; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLUpdateBotInlineQueryFlag)from.ReadInt32();
			QueryId = from.ReadInt64();
			UserId = from.ReadInt32();
			Query = from.ReadString();
			if (HasGeo) Geo = TLFactory.Read<TLGeoPointBase>(from);
			Offset = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			UpdateFlags();

			to.Write(0x54826690);
			to.Write((Int32)Flags);
			to.Write(QueryId);
			to.Write(UserId);
			to.Write(Query);
			if (HasGeo) to.WriteObject(Geo);
			to.Write(Offset);
		}

		private void UpdateFlags()
		{
			HasGeo = Geo != null;
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLUpdateBotInlineQueryFlag : Int32
	{
		Geo = (1 << 0),
	}
#endif

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateBotInlineQuery : TLUpdateBase
	{
		bool HasGeo { get; set; }

		TLUpdateBotInlineQueryFlag Flags { get; set; }
		Int64 QueryId { get; set; }
		Int32 UserId { get; set; }
		String Query { get; set; }
		TLGeoPointBase Geo { get; set; }
		String Offset { get; set; }
	}
#endif

}