// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateUserStatus : ITLUpdateBase, TLUpdateUserStatus 
	{
		public Int32 UserId { get; set; }
		public TLUserStatusBase Status { get; set; }

		public ITLUpdateUserStatus() { }
		public ITLUpdateUserStatus(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateUserStatus; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
			Status = TLFactory.Read<TLUserStatusBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x1BFBD823);
			to.Write(UserId);
			to.WriteObject(Status);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateUserStatus : TLUpdateBase
	{
		Int32 UserId { get; set; }
		TLUserStatusBase Status { get; set; }
	}
#endif

}