// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateChatParticipantAdmin : ITLUpdateBase, TLUpdateChatParticipantAdmin 
	{
		public Int32 ChatId { get; set; }
		public Int32 UserId { get; set; }
		public Boolean IsAdmin { get; set; }
		public Int32 Version { get; set; }

		public ITLUpdateChatParticipantAdmin() { }
		public ITLUpdateChatParticipantAdmin(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateChatParticipantAdmin; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
			UserId = from.ReadInt32();
			IsAdmin = from.ReadBoolean();
			Version = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB6901959);
			to.Write(ChatId);
			to.Write(UserId);
			to.Write(IsAdmin);
			to.Write(Version);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateChatParticipantAdmin : TLUpdateBase
	{
		Int32 ChatId { get; set; }
		Int32 UserId { get; set; }
		Boolean IsAdmin { get; set; }
		Int32 Version { get; set; }
	}
#endif

}