// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateReadHistoryInbox : ITLUpdateBase, TLUpdateReadHistoryInbox, ITLMultiPts 
	{
		public TLPeerBase Peer { get; set; }
		public Int32 MaxId { get; set; }
		public Int32 Pts { get; set; }
		public Int32 PtsCount { get; set; }

		public ITLUpdateReadHistoryInbox() { }
		public ITLUpdateReadHistoryInbox(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateReadHistoryInbox; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLPeerBase>(from);
			MaxId = from.ReadInt32();
			Pts = from.ReadInt32();
			PtsCount = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9961FD5C);
			to.WriteObject(Peer);
			to.Write(MaxId);
			to.Write(Pts);
			to.Write(PtsCount);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateReadHistoryInbox : TLUpdateBase
	{
		TLPeerBase Peer { get; set; }
		Int32 MaxId { get; set; }
		Int32 Pts { get; set; }
		Int32 PtsCount { get; set; }
	}
#endif

}