// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUploadWebFile : ITLObject, TLUploadWebFile 
	{
		public Int32 Size { get; set; }
		public String MimeType { get; set; }
		public TLStorageFileTypeBase FileType { get; set; }
		public Int32 Mtime { get; set; }
		public Byte[] Bytes { get; set; }

		public ITLUploadWebFile() { }
		public ITLUploadWebFile(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UploadWebFile; } }

		public override void Read(TLBinaryReader from)
		{
			Size = from.ReadInt32();
			MimeType = from.ReadString();
			FileType = TLFactory.Read<TLStorageFileTypeBase>(from);
			Mtime = from.ReadInt32();
			Bytes = from.ReadByteArray();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x21E753BC);
			to.Write(Size);
			to.Write(MimeType);
			to.WriteObject(FileType);
			to.Write(Mtime);
			to.WriteByteArray(Bytes);
		}
	}

#if !PORTABLE
	[Guid(0xeb58472f, 0x1a7b, 0x44fd, 0x61, 0x65, 0xf4, 0x18, 0x1b, 0x13, 0x77, 0x52)]
	public partial interface TLUploadWebFile : TLObject
	{
		Int32 Size { get; set; }
		String MimeType { get; set; }
		TLStorageFileTypeBase FileType { get; set; }
		Int32 Mtime { get; set; }
		Byte[] Bytes { get; set; }
	}
#endif

}