// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateUserName : ITLUpdateBase, TLUpdateUserName 
	{
		public Int32 UserId { get; set; }
		public String FirstName { get; set; }
		public String LastName { get; set; }
		public String Username { get; set; }

		public ITLUpdateUserName() { }
		public ITLUpdateUserName(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateUserName; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
			FirstName = from.ReadString();
			LastName = from.ReadString();
			Username = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xA7332B73);
			to.Write(UserId);
			to.Write(FirstName);
			to.Write(LastName);
			to.Write(Username);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateUserName : TLUpdateBase
	{
		Int32 UserId { get; set; }
		String FirstName { get; set; }
		String LastName { get; set; }
		String Username { get; set; }
	}
#endif

}