// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateChatParticipantAdd : ITLUpdateBase, TLUpdateChatParticipantAdd 
	{
		public Int32 ChatId { get; set; }
		public Int32 UserId { get; set; }
		public Int32 InviterId { get; set; }
		public Int32 Date { get; set; }
		public Int32 Version { get; set; }

		public ITLUpdateChatParticipantAdd() { }
		public ITLUpdateChatParticipantAdd(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateChatParticipantAdd; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
			UserId = from.ReadInt32();
			InviterId = from.ReadInt32();
			Date = from.ReadInt32();
			Version = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEA4B0E5C);
			to.Write(ChatId);
			to.Write(UserId);
			to.Write(InviterId);
			to.Write(Date);
			to.Write(Version);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateChatParticipantAdd : TLUpdateBase
	{
		Int32 ChatId { get; set; }
		Int32 UserId { get; set; }
		Int32 InviterId { get; set; }
		Int32 Date { get; set; }
		Int32 Version { get; set; }
	}
#endif

}