// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateDraftMessage : ITLUpdateBase, TLUpdateDraftMessage 
	{
		public TLPeerBase Peer { get; set; }
		public TLDraftMessageBase Draft { get; set; }

		public ITLUpdateDraftMessage() { }
		public ITLUpdateDraftMessage(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateDraftMessage; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLPeerBase>(from);
			Draft = TLFactory.Read<TLDraftMessageBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEE2BB969);
			to.WriteObject(Peer);
			to.WriteObject(Draft);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateDraftMessage : TLUpdateBase
	{
		TLPeerBase Peer { get; set; }
		TLDraftMessageBase Draft { get; set; }
	}
#endif

}