// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateMessageID : ITLUpdateBase, TLUpdateMessageID 
	{
		public Int32 Id { get; set; }
		public Int64 RandomId { get; set; }

		public ITLUpdateMessageID() { }
		public ITLUpdateMessageID(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateMessageID; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt32();
			RandomId = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4E90BFD6);
			to.Write(Id);
			to.Write(RandomId);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateMessageID : TLUpdateBase
	{
		Int32 Id { get; set; }
		Int64 RandomId { get; set; }
	}
#endif

}