// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdateUserBlocked : ITLUpdateBase, TLUpdateUserBlocked 
	{
		public Int32 UserId { get; set; }
		public Boolean Blocked { get; set; }

		public ITLUpdateUserBlocked() { }
		public ITLUpdateUserBlocked(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdateUserBlocked; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = from.ReadInt32();
			Blocked = from.ReadBoolean();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x80ECE81A);
			to.Write(UserId);
			to.Write(Blocked);
		}
	}

#if !PORTABLE
	[Guid(0x8340c33a, 0x292f, 0x15c1, 0x38, 0xfb, 0xe2, 0xd6, 0xf7, 0x5e, 0x8b, 0xcc)]
	public partial interface TLUpdateUserBlocked : TLUpdateBase
	{
		Int32 UserId { get; set; }
		Boolean Blocked { get; set; }
	}
#endif

}