// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdatesCombined : ITLUpdatesBase, TLUpdatesCombined 
	{
		public TLVector<TLUpdateBase> Updates { get; set; }
		public TLVector<TLUserBase> Users { get; set; }
		public TLVector<TLChatBase> Chats { get; set; }
		public Int32 Date { get; set; }
		public Int32 SeqStart { get; set; }
		public Int32 Seq { get; set; }

		public ITLUpdatesCombined() { }
		public ITLUpdatesCombined(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdatesCombined; } }

		public override void Read(TLBinaryReader from)
		{
			Updates = TLFactory.Read<TLVector<TLUpdateBase>>(from);
			Users = TLFactory.Read<TLVector<TLUserBase>>(from);
			Chats = TLFactory.Read<TLVector<TLChatBase>>(from);
			Date = from.ReadInt32();
			SeqStart = from.ReadInt32();
			Seq = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x725B04C3);
			to.WriteObject(Updates);
			to.WriteObject(Users);
			to.WriteObject(Chats);
			to.Write(Date);
			to.Write(SeqStart);
			to.Write(Seq);
		}
	}

#if !PORTABLE
	[Guid(0xd35752d0, 0x0452, 0x6165, 0xb5, 0xbf, 0xa2, 0x65, 0x03, 0x22, 0xd8, 0x2d)]
	public partial interface TLUpdatesCombined : TLUpdatesBase
	{
		TLVector<TLUpdateBase> Updates { get; set; }
		TLVector<TLUserBase> Users { get; set; }
		TLVector<TLChatBase> Chats { get; set; }
		Int32 Date { get; set; }
		Int32 SeqStart { get; set; }
		Int32 Seq { get; set; }
	}
#endif

}