// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUserProfilePhotoEmpty : ITLUserProfilePhotoBase, TLUserProfilePhotoEmpty 
	{
		public ITLUserProfilePhotoEmpty() { }
		public ITLUserProfilePhotoEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UserProfilePhotoEmpty; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4F11BAE1);
		}
	}

#if !PORTABLE
	[Guid(0xd5eac316, 0x0b21, 0x7f27, 0x82, 0x7c, 0x72, 0x38, 0x87, 0x2d, 0x4b, 0x8a)]
	public partial interface TLUserProfilePhotoEmpty : TLUserProfilePhotoBase
	{
	}
#endif

}