// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUserStatusRecently : ITLUserStatusBase, TLUserStatusRecently 
	{
		public ITLUserStatusRecently() { }
		public ITLUserStatusRecently(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UserStatusRecently; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE26F42F1);
		}
	}

#if !PORTABLE
	[Guid(0xa1ae2f96, 0x4492, 0xb1eb, 0x0a, 0x3b, 0x21, 0xbf, 0x72, 0x0a, 0xbe, 0x66)]
	public partial interface TLUserStatusRecently : TLUserStatusBase
	{
	}
#endif

}