// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLWebPageEmpty : ITLWebPageBase, TLWebPageEmpty 
	{
		public ITLWebPageEmpty() { }
		public ITLWebPageEmpty(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.WebPageEmpty; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEB1477E8);
			to.Write(Id);
		}
	}

#if !PORTABLE
	[Guid(0x74412133, 0xc889, 0xfc4d, 0x30, 0x31, 0x61, 0xe1, 0x14, 0xb7, 0x72, 0xf2)]
	public partial interface TLWebPageEmpty : TLWebPageBase
	{
		Int64 Id { get; set; }
	}
#endif

}