// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL
{
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLWebPagePending : ITLWebPageBase, TLWebPagePending 
	{
		public Int32 Date { get; set; }

		public ITLWebPagePending() { }
		public ITLWebPagePending(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.WebPagePending; } }

		public override void Read(TLBinaryReader from)
		{
			Id = from.ReadInt64();
			Date = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xC586DA1C);
			to.Write(Id);
			to.Write(Date);
		}
	}

#if !PORTABLE
	[Guid(0x74412133, 0xc889, 0xfc4d, 0x30, 0x31, 0x61, 0xe1, 0x14, 0xb7, 0x72, 0xf2)]
	public partial interface TLWebPagePending : TLWebPageBase
	{
		Int64 Id { get; set; }
		Int32 Date { get; set; }
	}
#endif

}