// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Users
{
	/// <summary>
	/// RCP method users.getUsers.
	/// Returns <see cref="Telegram.Api.TL.TLVector<TLUser>"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUsersGetUsers : ITLObject, TLUsersGetUsers
	{
		public TLVector<TLInputUserBase> Id { get; set; }

		public ITLUsersGetUsers() { }
		public ITLUsersGetUsers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UsersGetUsers; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLVector<TLInputUserBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xD91A548);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0x7da820cc, 0x3271, 0x0b9d, 0x44, 0x1a, 0xeb, 0x17, 0x03, 0x6d, 0x98, 0xf9)]
	public partial interface TLUsersGetUsers : TLObject
	{
		TLVector<TLInputUserBase> Id { get; set; }
	}
#endif

}