// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Users
{
	/// <summary>
	/// RCP method users.getFullUser.
	/// Returns <see cref="Telegram.Api.TL.TLUserFull"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUsersGetFullUser : ITLObject, TLUsersGetFullUser
	{
		public TLInputUserBase Id { get; set; }

		public ITLUsersGetFullUser() { }
		public ITLUsersGetFullUser(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UsersGetFullUser; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLInputUserBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xCA30A5B1);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0xda813bb1, 0x6fbf, 0x27a6, 0x12, 0xea, 0xaf, 0x68, 0x75, 0xcc, 0xe7, 0x1d)]
	public partial interface TLUsersGetFullUser : TLObject
	{
		TLInputUserBase Id { get; set; }
	}
#endif

}