// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Contest
{
	/// <summary>
	/// RCP method contest.saveDeveloperInfo.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLContestSaveDeveloperInfo : ITLObject, TLContestSaveDeveloperInfo
	{
		public Int32 VkId { get; set; }
		public String Name { get; set; }
		public String PhoneNumber { get; set; }
		public Int32 Age { get; set; }
		public String City { get; set; }

		public ITLContestSaveDeveloperInfo() { }
		public ITLContestSaveDeveloperInfo(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ContestSaveDeveloperInfo; } }

		public override void Read(TLBinaryReader from)
		{
			VkId = from.ReadInt32();
			Name = from.ReadString();
			PhoneNumber = from.ReadString();
			Age = from.ReadInt32();
			City = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x9A5F6E95);
			to.Write(VkId);
			to.Write(Name);
			to.Write(PhoneNumber);
			to.Write(Age);
			to.Write(City);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLContestSaveDeveloperInfo : TLObject
	{
		Int32 VkId { get; set; }
		String Name { get; set; }
		String PhoneNumber { get; set; }
		Int32 Age { get; set; }
		String City { get; set; }
	}
#endif

}