// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Updates
{
	/// <summary>
	/// RCP method updates.getState.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesState"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUpdatesGetState : ITLObject, TLUpdatesGetState
	{
		public ITLUpdatesGetState() { }
		public ITLUpdatesGetState(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UpdatesGetState; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEDD4882A);
		}
	}

#if !PORTABLE
	[Guid(0xb4a71dfe, 0x8ec8, 0x4663, 0x83, 0x0a, 0xd2, 0x56, 0xd7, 0x9c, 0xf9, 0x71)]
	public partial interface TLUpdatesGetState : TLObject
	{
	}
#endif

}