// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods
{
	/// <summary>
	/// RCP method get_future_salts.
	/// Returns <see cref="Telegram.Api.TL.TLFutureSalts"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLGetFutureSalts : ITLObject, TLGetFutureSalts
	{
		public Int32 Num { get; set; }

		public ITLGetFutureSalts() { }
		public ITLGetFutureSalts(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.GetFutureSalts; } }

		public override void Read(TLBinaryReader from)
		{
			Num = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB921BD04);
			to.Write(Num);
		}
	}

#if !PORTABLE
	[Guid(0xc36c535d, 0x659c, 0x6f5b, 0xac, 0x76, 0xf9, 0x69, 0x60, 0x81, 0xb9, 0x6c)]
	public partial interface TLGetFutureSalts : TLObject
	{
		Int32 Num { get; set; }
	}
#endif

}