// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods
{
	/// <summary>
	/// RCP method ping.
	/// Returns <see cref="Telegram.Api.TL.TLPong"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPing : ITLObject, TLPing
	{
		public Int64 PingId { get; set; }

		public ITLPing() { }
		public ITLPing(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.Ping; } }

		public override void Read(TLBinaryReader from)
		{
			PingId = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x7ABE77EC);
			to.Write(PingId);
		}
	}

#if !PORTABLE
	[Guid(0x7a08db6f, 0xfba3, 0xcbfb, 0x82, 0x87, 0xa5, 0x93, 0xa0, 0x91, 0x9e, 0x61)]
	public partial interface TLPing : TLObject
	{
		Int64 PingId { get; set; }
	}
#endif

}