// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods
{
	/// <summary>
	/// RCP method req_pq.
	/// Returns <see cref="Telegram.Api.TL.TLResPQ"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLReqPQ : ITLObject, TLReqPQ
	{
		public TLInt128 Nonce { get; set; }

		public ITLReqPQ() { }
		public ITLReqPQ(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ReqPQ; } }

		public override void Read(TLBinaryReader from)
		{
			Nonce = TLFactory.Read<TLInt128>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x60469778);
			to.WriteObject(Nonce);
		}
	}

#if !PORTABLE
	[Guid(0x2be8d2b5, 0x4558, 0xe809, 0xe6, 0x7f, 0xe1, 0xd0, 0x00, 0x34, 0xf9, 0x8c)]
	public partial interface TLReqPQ : TLObject
	{
		TLInt128 Nonce { get; set; }
	}
#endif

}