// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Payments
{
	/// <summary>
	/// RCP method payments.getPaymentReceipt.
	/// Returns <see cref="Telegram.Api.TL.TLPaymentsPaymentReceipt"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPaymentsGetPaymentReceipt : ITLObject, TLPaymentsGetPaymentReceipt
	{
		public Int32 MsgId { get; set; }

		public ITLPaymentsGetPaymentReceipt() { }
		public ITLPaymentsGetPaymentReceipt(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PaymentsGetPaymentReceipt; } }

		public override void Read(TLBinaryReader from)
		{
			MsgId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xA092A980);
			to.Write(MsgId);
		}
	}

#if !PORTABLE
	[Guid(0xb8511f34, 0x5c20, 0x7dc5, 0x31, 0x4f, 0x21, 0x71, 0xff, 0x65, 0xa3, 0x0f)]
	public partial interface TLPaymentsGetPaymentReceipt : TLObject
	{
		Int32 MsgId { get; set; }
	}
#endif

}