// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Upload
{
	/// <summary>
	/// RCP method upload.getFile.
	/// Returns <see cref="Telegram.Api.TL.TLUploadFile"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUploadGetFile : ITLObject, TLUploadGetFile
	{
		public TLInputFileLocationBase Location { get; set; }
		public Int32 Offset { get; set; }
		public Int32 Limit { get; set; }

		public ITLUploadGetFile() { }
		public ITLUploadGetFile(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UploadGetFile; } }

		public override void Read(TLBinaryReader from)
		{
			Location = TLFactory.Read<TLInputFileLocationBase>(from);
			Offset = from.ReadInt32();
			Limit = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE3A6CFB5);
			to.WriteObject(Location);
			to.Write(Offset);
			to.Write(Limit);
		}
	}

#if !PORTABLE
	[Guid(0x56bc10c3, 0x01a5, 0xb973, 0xc7, 0x40, 0x2d, 0x14, 0xef, 0x35, 0x89, 0x1d)]
	public partial interface TLUploadGetFile : TLObject
	{
		TLInputFileLocationBase Location { get; set; }
		Int32 Offset { get; set; }
		Int32 Limit { get; set; }
	}
#endif

}