// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Upload
{
	/// <summary>
	/// RCP method upload.saveFilePart.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLUploadSaveFilePart : ITLObject, TLUploadSaveFilePart
	{
		public Int64 FileId { get; set; }
		public Int32 FilePart { get; set; }
		public Byte[] Bytes { get; set; }

		public ITLUploadSaveFilePart() { }
		public ITLUploadSaveFilePart(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.UploadSaveFilePart; } }

		public override void Read(TLBinaryReader from)
		{
			FileId = from.ReadInt64();
			FilePart = from.ReadInt32();
			Bytes = from.ReadByteArray();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xB304A621);
			to.Write(FileId);
			to.Write(FilePart);
			to.WriteByteArray(Bytes);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLUploadSaveFilePart : TLObject
	{
		Int64 FileId { get; set; }
		Int32 FilePart { get; set; }
		Byte[] Bytes { get; set; }
	}
#endif

}