// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Phone
{
	/// <summary>
	/// RCP method phone.receivedCall.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPhoneReceivedCall : ITLObject, TLPhoneReceivedCall
	{
		public TLInputPhoneCall Peer { get; set; }

		public ITLPhoneReceivedCall() { }
		public ITLPhoneReceivedCall(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhoneReceivedCall; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputPhoneCall>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x17D54F61);
			to.WriteObject(Peer);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLPhoneReceivedCall : TLObject
	{
		TLInputPhoneCall Peer { get; set; }
	}
#endif

}