// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Phone
{
	/// <summary>
	/// RCP method phone.saveCallDebug.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLPhoneSaveCallDebug : ITLObject, TLPhoneSaveCallDebug
	{
		public TLInputPhoneCall Peer { get; set; }
		public TLDataJSON Debug { get; set; }

		public ITLPhoneSaveCallDebug() { }
		public ITLPhoneSaveCallDebug(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.PhoneSaveCallDebug; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputPhoneCall>(from);
			Debug = TLFactory.Read<TLDataJSON>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x277ADD7E);
			to.WriteObject(Peer);
			to.WriteObject(Debug);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLPhoneSaveCallDebug : TLObject
	{
		TLInputPhoneCall Peer { get; set; }
		TLDataJSON Debug { get; set; }
	}
#endif

}