// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Auth
{
	/// <summary>
	/// RCP method auth.sendInvites.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAuthSendInvites : ITLObject, TLAuthSendInvites
	{
		public TLVector<String> PhoneNumbers { get; set; }
		public String Message { get; set; }

		public ITLAuthSendInvites() { }
		public ITLAuthSendInvites(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AuthSendInvites; } }

		public override void Read(TLBinaryReader from)
		{
			PhoneNumbers = TLFactory.Read<TLVector<String>>(from);
			Message = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x771C1D97);
			to.WriteObject(PhoneNumbers);
			to.Write(Message);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLAuthSendInvites : TLObject
	{
		TLVector<String> PhoneNumbers { get; set; }
		String Message { get; set; }
	}
#endif

}