// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Auth
{
	/// <summary>
	/// RCP method auth.requestPasswordRecovery.
	/// Returns <see cref="Telegram.Api.TL.TLAuthPasswordRecovery"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAuthRequestPasswordRecovery : ITLObject, TLAuthRequestPasswordRecovery
	{
		public ITLAuthRequestPasswordRecovery() { }
		public ITLAuthRequestPasswordRecovery(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AuthRequestPasswordRecovery; } }

		public override void Read(TLBinaryReader from)
		{
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xD897BC66);
		}
	}

#if !PORTABLE
	[Guid(0x169fe355, 0xb2b5, 0x263d, 0x6b, 0x73, 0xab, 0x65, 0x3a, 0x33, 0x27, 0xf0)]
	public partial interface TLAuthRequestPasswordRecovery : TLObject
	{
	}
#endif

}