// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Auth
{
	/// <summary>
	/// RCP method auth.checkPassword.
	/// Returns <see cref="Telegram.Api.TL.TLAuthAuthorization"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAuthCheckPassword : ITLObject, TLAuthCheckPassword
	{
		public Byte[] PasswordHash { get; set; }

		public ITLAuthCheckPassword() { }
		public ITLAuthCheckPassword(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AuthCheckPassword; } }

		public override void Read(TLBinaryReader from)
		{
			PasswordHash = from.ReadByteArray();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xA63011E);
			to.WriteByteArray(PasswordHash);
		}
	}

#if !PORTABLE
	[Guid(0x6798571d, 0xf859, 0x4598, 0xde, 0x4d, 0x0b, 0xba, 0xee, 0xd9, 0x3b, 0x85)]
	public partial interface TLAuthCheckPassword : TLObject
	{
		Byte[] PasswordHash { get; set; }
	}
#endif

}