// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Auth
{
	/// <summary>
	/// RCP method auth.signIn.
	/// Returns <see cref="Telegram.Api.TL.TLAuthAuthorization"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLAuthSignIn : ITLObject, TLAuthSignIn
	{
		public String PhoneNumber { get; set; }
		public String PhoneCodeHash { get; set; }
		public String PhoneCode { get; set; }

		public ITLAuthSignIn() { }
		public ITLAuthSignIn(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AuthSignIn; } }

		public override void Read(TLBinaryReader from)
		{
			PhoneNumber = from.ReadString();
			PhoneCodeHash = from.ReadString();
			PhoneCode = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xBCD51581);
			to.Write(PhoneNumber);
			to.Write(PhoneCodeHash);
			to.Write(PhoneCode);
		}
	}

#if !PORTABLE
	[Guid(0x6798571d, 0xf859, 0x4598, 0xde, 0x4d, 0x0b, 0xba, 0xee, 0xd9, 0x3b, 0x85)]
	public partial interface TLAuthSignIn : TLObject
	{
		String PhoneNumber { get; set; }
		String PhoneCodeHash { get; set; }
		String PhoneCode { get; set; }
	}
#endif

}