// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Channels
{
	/// <summary>
	/// RCP method channels.editTitle.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChannelsEditTitle : ITLObject, TLChannelsEditTitle
	{
		public TLInputChannelBase Channel { get; set; }
		public String Title { get; set; }

		public ITLChannelsEditTitle() { }
		public ITLChannelsEditTitle(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelsEditTitle; } }

		public override void Read(TLBinaryReader from)
		{
			Channel = TLFactory.Read<TLInputChannelBase>(from);
			Title = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x566DECD0);
			to.WriteObject(Channel);
			to.Write(Title);
		}
	}

#if !PORTABLE
	[Guid(0xd35752d0, 0x0452, 0x6165, 0xb5, 0xbf, 0xa2, 0x65, 0x03, 0x22, 0xd8, 0x2d)]
	public partial interface TLChannelsEditTitle : TLObject
	{
		TLInputChannelBase Channel { get; set; }
		String Title { get; set; }
	}
#endif

}