// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Channels
{
	/// <summary>
	/// RCP method channels.getParticipant.
	/// Returns <see cref="Telegram.Api.TL.TLChannelsChannelParticipant"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChannelsGetParticipant : ITLObject, TLChannelsGetParticipant
	{
		public TLInputChannelBase Channel { get; set; }
		public TLInputUserBase UserId { get; set; }

		public ITLChannelsGetParticipant() { }
		public ITLChannelsGetParticipant(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelsGetParticipant; } }

		public override void Read(TLBinaryReader from)
		{
			Channel = TLFactory.Read<TLInputChannelBase>(from);
			UserId = TLFactory.Read<TLInputUserBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x546DD7A6);
			to.WriteObject(Channel);
			to.WriteObject(UserId);
		}
	}

#if !PORTABLE
	[Guid(0x2fa0c252, 0x9201, 0x216c, 0xf5, 0x91, 0x0a, 0x18, 0x21, 0xbb, 0xb1, 0xb6)]
	public partial interface TLChannelsGetParticipant : TLObject
	{
		TLInputChannelBase Channel { get; set; }
		TLInputUserBase UserId { get; set; }
	}
#endif

}