// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Channels
{
	/// <summary>
	/// RCP method channels.editAdmin.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChannelsEditAdmin : ITLObject, TLChannelsEditAdmin
	{
		public TLInputChannelBase Channel { get; set; }
		public TLInputUserBase UserId { get; set; }
		public TLChannelParticipantRoleBase Role { get; set; }

		public ITLChannelsEditAdmin() { }
		public ITLChannelsEditAdmin(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelsEditAdmin; } }

		public override void Read(TLBinaryReader from)
		{
			Channel = TLFactory.Read<TLInputChannelBase>(from);
			UserId = TLFactory.Read<TLInputUserBase>(from);
			Role = TLFactory.Read<TLChannelParticipantRoleBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xEB7611D0);
			to.WriteObject(Channel);
			to.WriteObject(UserId);
			to.WriteObject(Role);
		}
	}

#if !PORTABLE
	[Guid(0xd35752d0, 0x0452, 0x6165, 0xb5, 0xbf, 0xa2, 0x65, 0x03, 0x22, 0xd8, 0x2d)]
	public partial interface TLChannelsEditAdmin : TLObject
	{
		TLInputChannelBase Channel { get; set; }
		TLInputUserBase UserId { get; set; }
		TLChannelParticipantRoleBase Role { get; set; }
	}
#endif

}