// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Channels
{
	/// <summary>
	/// RCP method channels.toggleSignatures.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChannelsToggleSignatures : ITLObject, TLChannelsToggleSignatures
	{
		public TLInputChannelBase Channel { get; set; }
		public Boolean Enabled { get; set; }

		public ITLChannelsToggleSignatures() { }
		public ITLChannelsToggleSignatures(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelsToggleSignatures; } }

		public override void Read(TLBinaryReader from)
		{
			Channel = TLFactory.Read<TLInputChannelBase>(from);
			Enabled = from.ReadBoolean();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x1F69B606);
			to.WriteObject(Channel);
			to.Write(Enabled);
		}
	}

#if !PORTABLE
	[Guid(0xd35752d0, 0x0452, 0x6165, 0xb5, 0xbf, 0xa2, 0x65, 0x03, 0x22, 0xd8, 0x2d)]
	public partial interface TLChannelsToggleSignatures : TLObject
	{
		TLInputChannelBase Channel { get; set; }
		Boolean Enabled { get; set; }
	}
#endif

}