// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Channels
{
	/// <summary>
	/// RCP method channels.readHistory.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLChannelsReadHistory : ITLObject, TLChannelsReadHistory
	{
		public TLInputChannelBase Channel { get; set; }
		public Int32 MaxId { get; set; }

		public ITLChannelsReadHistory() { }
		public ITLChannelsReadHistory(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.ChannelsReadHistory; } }

		public override void Read(TLBinaryReader from)
		{
			Channel = TLFactory.Read<TLInputChannelBase>(from);
			MaxId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xCC104937);
			to.WriteObject(Channel);
			to.Write(MaxId);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLChannelsReadHistory : TLObject
	{
		TLInputChannelBase Channel { get; set; }
		Int32 MaxId { get; set; }
	}
#endif

}