// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.requestEncryption.
	/// Returns <see cref="Telegram.Api.TL.TLEncryptedChatBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesRequestEncryption : ITLObject, TLMessagesRequestEncryption
	{
		public TLInputUserBase UserId { get; set; }
		public Int32 RandomId { get; set; }
		public Byte[] GA { get; set; }

		public ITLMessagesRequestEncryption() { }
		public ITLMessagesRequestEncryption(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesRequestEncryption; } }

		public override void Read(TLBinaryReader from)
		{
			UserId = TLFactory.Read<TLInputUserBase>(from);
			RandomId = from.ReadInt32();
			GA = from.ReadByteArray();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xF64DAF43);
			to.WriteObject(UserId);
			to.Write(RandomId);
			to.WriteByteArray(GA);
		}
	}

#if !PORTABLE
	[Guid(0xa0e8d796, 0x017e, 0xa6c4, 0x86, 0x9a, 0x55, 0x64, 0xec, 0xf4, 0xac, 0x7f)]
	public partial interface TLMessagesRequestEncryption : TLObject
	{
		TLInputUserBase UserId { get; set; }
		Int32 RandomId { get; set; }
		Byte[] GA { get; set; }
	}
#endif

}