// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getWebPagePreview.
	/// Returns <see cref="Telegram.Api.TL.TLMessageMediaBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetWebPagePreview : ITLObject, TLMessagesGetWebPagePreview
	{
		public String Message { get; set; }

		public ITLMessagesGetWebPagePreview() { }
		public ITLMessagesGetWebPagePreview(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetWebPagePreview; } }

		public override void Read(TLBinaryReader from)
		{
			Message = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x25223E24);
			to.Write(Message);
		}
	}

#if !PORTABLE
	[Guid(0xc59dc1cb, 0xf129, 0xf361, 0xcc, 0x4f, 0x3e, 0xaa, 0x83, 0x64, 0x9d, 0xe7)]
	public partial interface TLMessagesGetWebPagePreview : TLObject
	{
		String Message { get; set; }
	}
#endif

}