// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getHistory.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesMessages"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetHistory : ITLObject, TLMessagesGetHistory
	{
		public TLInputPeerBase Peer { get; set; }
		public Int32 OffsetId { get; set; }
		public Int32 OffsetDate { get; set; }
		public Int32 AddOffset { get; set; }
		public Int32 Limit { get; set; }
		public Int32 MaxId { get; set; }
		public Int32 MinId { get; set; }

		public ITLMessagesGetHistory() { }
		public ITLMessagesGetHistory(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetHistory; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputPeerBase>(from);
			OffsetId = from.ReadInt32();
			OffsetDate = from.ReadInt32();
			AddOffset = from.ReadInt32();
			Limit = from.ReadInt32();
			MaxId = from.ReadInt32();
			MinId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xAFA92846);
			to.WriteObject(Peer);
			to.Write(OffsetId);
			to.Write(OffsetDate);
			to.Write(AddOffset);
			to.Write(Limit);
			to.Write(MaxId);
			to.Write(MinId);
		}
	}

#if !PORTABLE
	[Guid(0x136920a5, 0xc016, 0xafe2, 0x62, 0x0d, 0xf2, 0x74, 0x96, 0xa0, 0x45, 0x01)]
	public partial interface TLMessagesGetHistory : TLObject
	{
		TLInputPeerBase Peer { get; set; }
		Int32 OffsetId { get; set; }
		Int32 OffsetDate { get; set; }
		Int32 AddOffset { get; set; }
		Int32 Limit { get; set; }
		Int32 MaxId { get; set; }
		Int32 MinId { get; set; }
	}
#endif

}