// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getStickerSet.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesStickerSet"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetStickerSet : ITLObject, TLMessagesGetStickerSet
	{
		public TLInputStickerSetBase StickerSet { get; set; }

		public ITLMessagesGetStickerSet() { }
		public ITLMessagesGetStickerSet(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetStickerSet; } }

		public override void Read(TLBinaryReader from)
		{
			StickerSet = TLFactory.Read<TLInputStickerSetBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x2619A90E);
			to.WriteObject(StickerSet);
		}
	}

#if !PORTABLE
	[Guid(0xdb27ecf3, 0xbb90, 0x1401, 0x1f, 0xea, 0xc0, 0x41, 0x2b, 0xa9, 0x2a, 0xd4)]
	public partial interface TLMessagesGetStickerSet : TLObject
	{
		TLInputStickerSetBase StickerSet { get; set; }
	}
#endif

}