// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.clearRecentStickers.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesClearRecentStickers : ITLObject, TLMessagesClearRecentStickers
	{
		public bool IsAttached { get { return Flags.HasFlag(TLMessagesClearRecentStickersFlag.Attached); } set { Flags = value ? (Flags | TLMessagesClearRecentStickersFlag.Attached) : (Flags & ~TLMessagesClearRecentStickersFlag.Attached); } }

		public TLMessagesClearRecentStickersFlag Flags { get; set; }

		public ITLMessagesClearRecentStickers() { }
		public ITLMessagesClearRecentStickers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesClearRecentStickers; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLMessagesClearRecentStickersFlag)from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x8999602D);
			to.Write((Int32)Flags);
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLMessagesClearRecentStickersFlag : Int32
	{
		Attached = (1 << 0),
	}
#endif

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLMessagesClearRecentStickers : TLObject
	{
		bool IsAttached { get; set; }

		TLMessagesClearRecentStickersFlag Flags { get; set; }
	}
#endif

}