// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.reorderStickerSets.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesReorderStickerSets : ITLObject, TLMessagesReorderStickerSets
	{
		public bool IsMasks { get { return Flags.HasFlag(TLMessagesReorderStickerSetsFlag.Masks); } set { Flags = value ? (Flags | TLMessagesReorderStickerSetsFlag.Masks) : (Flags & ~TLMessagesReorderStickerSetsFlag.Masks); } }

		public TLMessagesReorderStickerSetsFlag Flags { get; set; }
		public TLVector<Int64> Order { get; set; }

		public ITLMessagesReorderStickerSets() { }
		public ITLMessagesReorderStickerSets(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesReorderStickerSets; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLMessagesReorderStickerSetsFlag)from.ReadInt32();
			Order = TLFactory.Read<TLVector<Int64>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x78337739);
			to.Write((Int32)Flags);
			to.WriteObject(Order);
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLMessagesReorderStickerSetsFlag : Int32
	{
		Masks = (1 << 0),
	}
#endif

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLMessagesReorderStickerSets : TLObject
	{
		bool IsMasks { get; set; }

		TLMessagesReorderStickerSetsFlag Flags { get; set; }
		TLVector<Int64> Order { get; set; }
	}
#endif

}