// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.reportEncryptedSpam.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesReportEncryptedSpam : ITLObject, TLMessagesReportEncryptedSpam
	{
		public TLInputEncryptedChat Peer { get; set; }

		public ITLMessagesReportEncryptedSpam() { }
		public ITLMessagesReportEncryptedSpam(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesReportEncryptedSpam; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputEncryptedChat>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x4B0C8C0F);
			to.WriteObject(Peer);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLMessagesReportEncryptedSpam : TLObject
	{
		TLInputEncryptedChat Peer { get; set; }
	}
#endif

}