// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getMessageEditData.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesMessageEditData"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetMessageEditData : ITLObject, TLMessagesGetMessageEditData
	{
		public TLInputPeerBase Peer { get; set; }
		public Int32 Id { get; set; }

		public ITLMessagesGetMessageEditData() { }
		public ITLMessagesGetMessageEditData(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetMessageEditData; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputPeerBase>(from);
			Id = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xFDA68D36);
			to.WriteObject(Peer);
			to.Write(Id);
		}
	}

#if !PORTABLE
	[Guid(0x3a716c06, 0x909a, 0x8d5f, 0x27, 0x1b, 0xe1, 0xed, 0x60, 0x7f, 0x8f, 0xc1)]
	public partial interface TLMessagesGetMessageEditData : TLObject
	{
		TLInputPeerBase Peer { get; set; }
		Int32 Id { get; set; }
	}
#endif

}