// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getWebPage.
	/// Returns <see cref="Telegram.Api.TL.TLWebPageBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetWebPage : ITLObject, TLMessagesGetWebPage
	{
		public String Url { get; set; }
		public Int32 Hash { get; set; }

		public ITLMessagesGetWebPage() { }
		public ITLMessagesGetWebPage(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetWebPage; } }

		public override void Read(TLBinaryReader from)
		{
			Url = from.ReadString();
			Hash = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x32CA8F91);
			to.Write(Url);
			to.Write(Hash);
		}
	}

#if !PORTABLE
	[Guid(0x74412133, 0xc889, 0xfc4d, 0x30, 0x31, 0x61, 0xe1, 0x14, 0xb7, 0x72, 0xf2)]
	public partial interface TLMessagesGetWebPage : TLObject
	{
		String Url { get; set; }
		Int32 Hash { get; set; }
	}
#endif

}