// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getPeerDialogs.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesPeerDialogs"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetPeerDialogs : ITLObject, TLMessagesGetPeerDialogs
	{
		public TLVector<TLInputPeerBase> Peers { get; set; }

		public ITLMessagesGetPeerDialogs() { }
		public ITLMessagesGetPeerDialogs(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetPeerDialogs; } }

		public override void Read(TLBinaryReader from)
		{
			Peers = TLFactory.Read<TLVector<TLInputPeerBase>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x2D9776B9);
			to.WriteObject(Peers);
		}
	}

#if !PORTABLE
	[Guid(0x3f13d0f6, 0x673c, 0x82d8, 0x30, 0x01, 0xb3, 0x6d, 0xfd, 0x16, 0x9e, 0xc8)]
	public partial interface TLMessagesGetPeerDialogs : TLObject
	{
		TLVector<TLInputPeerBase> Peers { get; set; }
	}
#endif

}