// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.receivedQueue.
	/// Returns <see cref="Telegram.Api.TL.TLVector<TLlong>"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesReceivedQueue : ITLObject, TLMessagesReceivedQueue
	{
		public Int32 MaxQts { get; set; }

		public ITLMessagesReceivedQueue() { }
		public ITLMessagesReceivedQueue(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesReceivedQueue; } }

		public override void Read(TLBinaryReader from)
		{
			MaxQts = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x55A5BB66);
			to.Write(MaxQts);
		}
	}

#if !PORTABLE
	[Guid(0x700b902d, 0xc657, 0x07f5, 0xab, 0x50, 0xd4, 0xd0, 0x53, 0x7a, 0xa0, 0xaf)]
	public partial interface TLMessagesReceivedQueue : TLObject
	{
		Int32 MaxQts { get; set; }
	}
#endif

}