// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getDhConfig.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesDHConfigBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetDHConfig : ITLObject, TLMessagesGetDHConfig
	{
		public Int32 Version { get; set; }
		public Int32 RandomLength { get; set; }

		public ITLMessagesGetDHConfig() { }
		public ITLMessagesGetDHConfig(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetDHConfig; } }

		public override void Read(TLBinaryReader from)
		{
			Version = from.ReadInt32();
			RandomLength = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x26CF8950);
			to.Write(Version);
			to.Write(RandomLength);
		}
	}

#if !PORTABLE
	[Guid(0x0c37b574, 0xf5c1, 0x6b22, 0x3b, 0xc0, 0xf1, 0x96, 0x99, 0x76, 0x3e, 0x77)]
	public partial interface TLMessagesGetDHConfig : TLObject
	{
		Int32 Version { get; set; }
		Int32 RandomLength { get; set; }
	}
#endif

}