// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.toggleDialogPin.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesToggleDialogPin : ITLObject, TLMessagesToggleDialogPin
	{
		public bool IsPinned { get { return Flags.HasFlag(TLMessagesToggleDialogPinFlag.Pinned); } set { Flags = value ? (Flags | TLMessagesToggleDialogPinFlag.Pinned) : (Flags & ~TLMessagesToggleDialogPinFlag.Pinned); } }

		public TLMessagesToggleDialogPinFlag Flags { get; set; }
		public TLInputPeerBase Peer { get; set; }

		public ITLMessagesToggleDialogPin() { }
		public ITLMessagesToggleDialogPin(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesToggleDialogPin; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLMessagesToggleDialogPinFlag)from.ReadInt32();
			Peer = TLFactory.Read<TLInputPeerBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3289BE6A);
			to.Write((Int32)Flags);
			to.WriteObject(Peer);
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLMessagesToggleDialogPinFlag : Int32
	{
		Pinned = (1 << 0),
	}
#endif

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLMessagesToggleDialogPin : TLObject
	{
		bool IsPinned { get; set; }

		TLMessagesToggleDialogPinFlag Flags { get; set; }
		TLInputPeerBase Peer { get; set; }
	}
#endif

}