// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.editChatTitle.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesEditChatTitle : ITLObject, TLMessagesEditChatTitle
	{
		public Int32 ChatId { get; set; }
		public String Title { get; set; }

		public ITLMessagesEditChatTitle() { }
		public ITLMessagesEditChatTitle(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesEditChatTitle; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
			Title = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xDC452855);
			to.Write(ChatId);
			to.Write(Title);
		}
	}

#if !PORTABLE
	[Guid(0xd35752d0, 0x0452, 0x6165, 0xb5, 0xbf, 0xa2, 0x65, 0x03, 0x22, 0xd8, 0x2d)]
	public partial interface TLMessagesEditChatTitle : TLObject
	{
		Int32 ChatId { get; set; }
		String Title { get; set; }
	}
#endif

}