// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getAllStickers.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesAllStickersBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetAllStickers : ITLObject, TLMessagesGetAllStickers
	{
		public Int32 Hash { get; set; }

		public ITLMessagesGetAllStickers() { }
		public ITLMessagesGetAllStickers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetAllStickers; } }

		public override void Read(TLBinaryReader from)
		{
			Hash = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x1C9618B1);
			to.Write(Hash);
		}
	}

#if !PORTABLE
	[Guid(0x4cb693f4, 0x4cf4, 0x94dc, 0xc0, 0xcc, 0xa7, 0x4d, 0xdb, 0x48, 0x74, 0xd8)]
	public partial interface TLMessagesGetAllStickers : TLObject
	{
		Int32 Hash { get; set; }
	}
#endif

}