// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.searchGifs.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesFoundGifs"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesSearchGifs : ITLObject, TLMessagesSearchGifs
	{
		public String Q { get; set; }
		public Int32 Offset { get; set; }

		public ITLMessagesSearchGifs() { }
		public ITLMessagesSearchGifs(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesSearchGifs; } }

		public override void Read(TLBinaryReader from)
		{
			Q = from.ReadString();
			Offset = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xBF9A776B);
			to.Write(Q);
			to.Write(Offset);
		}
	}

#if !PORTABLE
	[Guid(0x1f98fff3, 0x7f9d, 0x343b, 0x5b, 0x73, 0x4a, 0x45, 0xe4, 0x13, 0xc9, 0x5b)]
	public partial interface TLMessagesSearchGifs : TLObject
	{
		String Q { get; set; }
		Int32 Offset { get; set; }
	}
#endif

}