// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getFullChat.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesChatFull"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetFullChat : ITLObject, TLMessagesGetFullChat
	{
		public Int32 ChatId { get; set; }

		public ITLMessagesGetFullChat() { }
		public ITLMessagesGetFullChat(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetFullChat; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3B831C66);
			to.Write(ChatId);
		}
	}

#if !PORTABLE
	[Guid(0x12e975eb, 0x8c91, 0x38fa, 0xf6, 0x8f, 0x44, 0x4f, 0xb9, 0x36, 0xcf, 0xca)]
	public partial interface TLMessagesGetFullChat : TLObject
	{
		Int32 ChatId { get; set; }
	}
#endif

}