// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getFeaturedStickers.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesFeaturedStickersBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetFeaturedStickers : ITLObject, TLMessagesGetFeaturedStickers
	{
		public Int32 Hash { get; set; }

		public ITLMessagesGetFeaturedStickers() { }
		public ITLMessagesGetFeaturedStickers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetFeaturedStickers; } }

		public override void Read(TLBinaryReader from)
		{
			Hash = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x2DACCA4F);
			to.Write(Hash);
		}
	}

#if !PORTABLE
	[Guid(0x2a9c7d7f, 0xa127, 0x3bc4, 0xfe, 0x28, 0xc5, 0xe2, 0x67, 0x5e, 0xc5, 0x29)]
	public partial interface TLMessagesGetFeaturedStickers : TLObject
	{
		Int32 Hash { get; set; }
	}
#endif

}