// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.migrateChat.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesMigrateChat : ITLObject, TLMessagesMigrateChat
	{
		public Int32 ChatId { get; set; }

		public ITLMessagesMigrateChat() { }
		public ITLMessagesMigrateChat(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesMigrateChat; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x15A3B8E3);
			to.Write(ChatId);
		}
	}

#if !PORTABLE
	[Guid(0xd35752d0, 0x0452, 0x6165, 0xb5, 0xbf, 0xa2, 0x65, 0x03, 0x22, 0xd8, 0x2d)]
	public partial interface TLMessagesMigrateChat : TLObject
	{
		Int32 ChatId { get; set; }
	}
#endif

}