// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.checkChatInvite.
	/// Returns <see cref="Telegram.Api.TL.TLChatInviteBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesCheckChatInvite : ITLObject, TLMessagesCheckChatInvite
	{
		public String Hash { get; set; }

		public ITLMessagesCheckChatInvite() { }
		public ITLMessagesCheckChatInvite(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesCheckChatInvite; } }

		public override void Read(TLBinaryReader from)
		{
			Hash = from.ReadString();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x3EADB1BB);
			to.Write(Hash);
		}
	}

#if !PORTABLE
	[Guid(0x1933644a, 0xdc13, 0x2f7b, 0xa8, 0x04, 0x39, 0xe1, 0xc3, 0x1d, 0xde, 0xad)]
	public partial interface TLMessagesCheckChatInvite : TLObject
	{
		String Hash { get; set; }
	}
#endif

}