// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.getBotCallbackAnswer.
	/// Returns <see cref="Telegram.Api.TL.TLMessagesBotCallbackAnswer"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesGetBotCallbackAnswer : ITLObject, TLMessagesGetBotCallbackAnswer
	{
		public bool IsGame { get { return Flags.HasFlag(TLMessagesGetBotCallbackAnswerFlag.Game); } set { Flags = value ? (Flags | TLMessagesGetBotCallbackAnswerFlag.Game) : (Flags & ~TLMessagesGetBotCallbackAnswerFlag.Game); } }
		public bool HasData { get { return Flags.HasFlag(TLMessagesGetBotCallbackAnswerFlag.Data); } set { Flags = value ? (Flags | TLMessagesGetBotCallbackAnswerFlag.Data) : (Flags & ~TLMessagesGetBotCallbackAnswerFlag.Data); } }

		public TLMessagesGetBotCallbackAnswerFlag Flags { get; set; }
		public TLInputPeerBase Peer { get; set; }
		public Int32 MsgId { get; set; }
		public Byte[] Data { get; set; }

		public ITLMessagesGetBotCallbackAnswer() { }
		public ITLMessagesGetBotCallbackAnswer(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesGetBotCallbackAnswer; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLMessagesGetBotCallbackAnswerFlag)from.ReadInt32();
			Peer = TLFactory.Read<TLInputPeerBase>(from);
			MsgId = from.ReadInt32();
			if (HasData) Data = from.ReadByteArray();
		}

		public override void Write(TLBinaryWriter to)
		{
			UpdateFlags();

			to.Write(0x810A9FEC);
			to.Write((Int32)Flags);
			to.WriteObject(Peer);
			to.Write(MsgId);
			if (HasData) to.WriteByteArray(Data);
		}

		private void UpdateFlags()
		{
			HasData = Data != null;
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLMessagesGetBotCallbackAnswerFlag : Int32
	{
		Game = (1 << 1),
		Data = (1 << 0),
	}
#endif

#if !PORTABLE
	[Guid(0x70a08cb0, 0x4cf1, 0x3836, 0x86, 0x44, 0xe0, 0xf7, 0xb9, 0xb8, 0x88, 0x02)]
	public partial interface TLMessagesGetBotCallbackAnswer : TLObject
	{
		bool IsGame { get; set; }
		bool HasData { get; set; }

		TLMessagesGetBotCallbackAnswerFlag Flags { get; set; }
		TLInputPeerBase Peer { get; set; }
		Int32 MsgId { get; set; }
		Byte[] Data { get; set; }
	}
#endif

}