// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.setInlineGameScore.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesSetInlineGameScore : ITLObject, TLMessagesSetInlineGameScore
	{
		public bool IsEditMessage { get { return Flags.HasFlag(TLMessagesSetInlineGameScoreFlag.EditMessage); } set { Flags = value ? (Flags | TLMessagesSetInlineGameScoreFlag.EditMessage) : (Flags & ~TLMessagesSetInlineGameScoreFlag.EditMessage); } }
		public bool IsForce { get { return Flags.HasFlag(TLMessagesSetInlineGameScoreFlag.Force); } set { Flags = value ? (Flags | TLMessagesSetInlineGameScoreFlag.Force) : (Flags & ~TLMessagesSetInlineGameScoreFlag.Force); } }

		public TLMessagesSetInlineGameScoreFlag Flags { get; set; }
		public TLInputBotInlineMessageID Id { get; set; }
		public TLInputUserBase UserId { get; set; }
		public Int32 Score { get; set; }

		public ITLMessagesSetInlineGameScore() { }
		public ITLMessagesSetInlineGameScore(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesSetInlineGameScore; } }

		public override void Read(TLBinaryReader from)
		{
			Flags = (TLMessagesSetInlineGameScoreFlag)from.ReadInt32();
			Id = TLFactory.Read<TLInputBotInlineMessageID>(from);
			UserId = TLFactory.Read<TLInputUserBase>(from);
			Score = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x15AD9F64);
			to.Write((Int32)Flags);
			to.WriteObject(Id);
			to.WriteObject(UserId);
			to.Write(Score);
		}
	}

#if !PORTABLE
	[Flags]
	public enum TLMessagesSetInlineGameScoreFlag : Int32
	{
		EditMessage = (1 << 0),
		Force = (1 << 1),
	}
#endif

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLMessagesSetInlineGameScore : TLObject
	{
		bool IsEditMessage { get; set; }
		bool IsForce { get; set; }

		TLMessagesSetInlineGameScoreFlag Flags { get; set; }
		TLInputBotInlineMessageID Id { get; set; }
		TLInputUserBase UserId { get; set; }
		Int32 Score { get; set; }
	}
#endif

}