// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.readFeaturedStickers.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesReadFeaturedStickers : ITLObject, TLMessagesReadFeaturedStickers
	{
		public TLVector<Int64> Id { get; set; }

		public ITLMessagesReadFeaturedStickers() { }
		public ITLMessagesReadFeaturedStickers(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesReadFeaturedStickers; } }

		public override void Read(TLBinaryReader from)
		{
			Id = TLFactory.Read<TLVector<Int64>>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x5B118126);
			to.WriteObject(Id);
		}
	}

#if !PORTABLE
	[Guid(0x13ff06c5, 0xab4b, 0x6edd, 0x68, 0xab, 0x3e, 0x63, 0x50, 0xe9, 0x53, 0x05)]
	public partial interface TLMessagesReadFeaturedStickers : TLObject
	{
		TLVector<Int64> Id { get; set; }
	}
#endif

}