// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.deleteChatUser.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesDeleteChatUser : ITLObject, TLMessagesDeleteChatUser
	{
		public Int32 ChatId { get; set; }
		public TLInputUserBase UserId { get; set; }

		public ITLMessagesDeleteChatUser() { }
		public ITLMessagesDeleteChatUser(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesDeleteChatUser; } }

		public override void Read(TLBinaryReader from)
		{
			ChatId = from.ReadInt32();
			UserId = TLFactory.Read<TLInputUserBase>(from);
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0xE0611F16);
			to.Write(ChatId);
			to.WriteObject(UserId);
		}
	}

#if !PORTABLE
	[Guid(0xd35752d0, 0x0452, 0x6165, 0xb5, 0xbf, 0xa2, 0x65, 0x03, 0x22, 0xd8, 0x2d)]
	public partial interface TLMessagesDeleteChatUser : TLObject
	{
		Int32 ChatId { get; set; }
		TLInputUserBase UserId { get; set; }
	}
#endif

}