// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.receivedMessages.
	/// Returns <see cref="Telegram.Api.TL.TLVector<TLReceivedNotifyMessage>"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesReceivedMessages : ITLObject, TLMessagesReceivedMessages
	{
		public Int32 MaxId { get; set; }

		public ITLMessagesReceivedMessages() { }
		public ITLMessagesReceivedMessages(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesReceivedMessages; } }

		public override void Read(TLBinaryReader from)
		{
			MaxId = from.ReadInt32();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x5A954C0);
			to.Write(MaxId);
		}
	}

#if !PORTABLE
	[Guid(0x5f92e4ce, 0x34d1, 0xce29, 0x1c, 0x2e, 0x62, 0x04, 0x36, 0x2e, 0x1f, 0x43)]
	public partial interface TLMessagesReceivedMessages : TLObject
	{
		Int32 MaxId { get; set; }
	}
#endif

}