// <auto-generated/>
using System;
using Windows.Foundation.Metadata;

namespace Telegram.Api.TL.Methods.Messages
{
	/// <summary>
	/// RCP method messages.forwardMessage.
	/// Returns <see cref="Telegram.Api.TL.TLUpdatesBase"/>
	/// </summary>
#if !PORTABLE
	internal
#else
	public
#endif
	partial class ITLMessagesForwardMessage : ITLObject, TLMessagesForwardMessage
	{
		public TLInputPeerBase Peer { get; set; }
		public Int32 Id { get; set; }
		public Int64 RandomId { get; set; }

		public ITLMessagesForwardMessage() { }
		public ITLMessagesForwardMessage(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.MessagesForwardMessage; } }

		public override void Read(TLBinaryReader from)
		{
			Peer = TLFactory.Read<TLInputPeerBase>(from);
			Id = from.ReadInt32();
			RandomId = from.ReadInt64();
		}

		public override void Write(TLBinaryWriter to)
		{
			to.Write(0x33963BF9);
			to.WriteObject(Peer);
			to.Write(Id);
			to.Write(RandomId);
		}
	}

#if !PORTABLE
	[Guid(0xd35752d0, 0x0452, 0x6165, 0xb5, 0xbf, 0xa2, 0x65, 0x03, 0x22, 0xd8, 0x2d)]
	public partial interface TLMessagesForwardMessage : TLObject
	{
		TLInputPeerBase Peer { get; set; }
		Int32 Id { get; set; }
		Int64 RandomId { get; set; }
	}
#endif

}